<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Assignmentfeedback extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model(['Assignmentfeedback_model','Notification_model']);
    } 

    /*
     * Listing of assignmentfeedback
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('assignmentfeedback/index?');
        $config['total_rows'] = $this->Assignmentfeedback_model->get_all_assignmentfeedback_count();
        $this->pagination->initialize($config);

        $data['assignmentfeedback'] = $this->Assignmentfeedback_model->get_all_assignmentfeedback($params);
        
        $data['_view'] = 'assignmentfeedback/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new assignmentfeedback
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('total','Total','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'moduleID' => $this->input->post('moduleID'),
				'studentID' => $this->input->post('studentID'),
				'adminID' => $this->input->post('adminID'),
				'assignmentID' => $this->input->post('assignmentID'),
				'total' => $this->input->post('total'),
				'grade' => $this->input->post('grade'),
				'status' => $this->input->post('status'),
				'comment' => $this->input->post('comment'),
				'time_stamp' => $this->input->post('time_stamp'),
				'feedback' => $this->input->post('feedback'),
            );
            
            $assignmentfeedback_id = $this->Assignmentfeedback_model->add_assignmentfeedback($params);
            redirect('assignmentfeedback/index');
        }
        else
        {
			$this->load->model('Module_model');
			$data['all_modules'] = $this->Module_model->get_all_modules();

			$this->load->model('Student_model');
			$data['all_students'] = $this->Student_model->get_all_students();

			$this->load->model('User_model');
			$data['all_users'] = $this->User_model->get_all_users();

			$this->load->model('Assignment_model');
			$data['all_assignment'] = $this->Assignment_model->get_all_assignment();
            
            $data['_view'] = 'assignmentfeedback/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a assignmentfeedback
     */
    function edit($id)
    {   
        // check if the assignmentfeedback exists before trying to edit it
        $data['assignmentfeedback'] = $this->Assignmentfeedback_model->get_assignmentfeedback($id);
        
        if(isset($data['assignmentfeedback']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('total','Total','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'moduleID' => $this->input->post('moduleID'),
					'studentID' => $this->input->post('studentID'),
					'adminID' => $this->input->post('adminID'),
					'assignmentID' => $this->input->post('assignmentID'),
					'total' => $this->input->post('total'),
					'grade' => $this->input->post('grade'),
					'status' => $this->input->post('status'),
					'comment' => $this->input->post('comment'),
					'time_stamp' => $this->input->post('time_stamp'),
					'feedback' => $this->input->post('feedback'),
                );

                $this->Assignmentfeedback_model->update_assignmentfeedback($id,$params);            
                redirect('assignmentfeedback/index');
            }
            else
            {
				$this->load->model('Module_model');
				$data['all_modules'] = $this->Module_model->get_all_modules();

				$this->load->model('Student_model');
				$data['all_students'] = $this->Student_model->get_all_students();

				$this->load->model('User_model');
				$data['all_users'] = $this->User_model->get_all_users();

				$this->load->model('Assignment_model');
				$data['all_assignment'] = $this->Assignment_model->get_all_assignment();

                $data['_view'] = 'assignmentfeedback/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The assignmentfeedback you are trying to edit does not exist.');
    } 

    /*
     * Deleting assignmentfeedback
     */
    function remove($id)
    {
        $assignmentfeedback = $this->Assignmentfeedback_model->get_assignmentfeedback($id);

        // check if the assignmentfeedback exists before trying to delete it
        if(isset($assignmentfeedback['id']))
        {
            $this->Assignmentfeedback_model->delete_assignmentfeedback($id);
            redirect('assignmentfeedback/index');
        }
        else
            show_error('The assignmentfeedback you are trying to delete does not exist.');
    }
}
