<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Assignmentfile extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model(['Assignmentfile_model','Notification_model']);
    } 

    /*
     * Listing of assignmentfiles
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('assignmentfile/index?');
        $config['total_rows'] = $this->Assignmentfile_model->get_all_assignmentfiles_count();
        $this->pagination->initialize($config);

        $data['assignmentfiles'] = $this->Assignmentfile_model->get_all_assignmentfiles($params);
        
        $data['_view'] = 'assignmentfile/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new assignmentfile
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('assignmentID','AssignmentID','required');
		$this->form_validation->set_rules('file','File','required');
		$this->form_validation->set_rules('deleteStatus','DeleteStatus','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'assignmentID' => $this->input->post('assignmentID'),
				'studentID' => $this->input->post('studentID'),
				'file' => $this->input->post('file'),
				'deleteStatus' => $this->input->post('deleteStatus'),
				'time_stamp' => $this->input->post('time_stamp'),
            );
            
            $assignmentfile_id = $this->Assignmentfile_model->add_assignmentfile($params);
            redirect('assignmentfile/index');
        }
        else
        {
			$this->load->model('Assignment_model');
			$data['all_assignment'] = $this->Assignment_model->get_all_assignment();

			$this->load->model('Student_model');
			$data['all_students'] = $this->Student_model->get_all_students();
            
            $data['_view'] = 'assignmentfile/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a assignmentfile
     */
    function edit($fileID)
    {   
        // check if the assignmentfile exists before trying to edit it
        $data['assignmentfile'] = $this->Assignmentfile_model->get_assignmentfile($fileID);
        
        if(isset($data['assignmentfile']['fileID']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('assignmentID','AssignmentID','required');
			$this->form_validation->set_rules('file','File','required');
			$this->form_validation->set_rules('deleteStatus','DeleteStatus','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'assignmentID' => $this->input->post('assignmentID'),
					'studentID' => $this->input->post('studentID'),
					'file' => $this->input->post('file'),
					'deleteStatus' => $this->input->post('deleteStatus'),
					'time_stamp' => $this->input->post('time_stamp'),
                );

                $this->Assignmentfile_model->update_assignmentfile($fileID,$params);            
                redirect('assignmentfile/index');
            }
            else
            {
				$this->load->model('Assignment_model');
				$data['all_assignment'] = $this->Assignment_model->get_all_assignment();

				$this->load->model('Student_model');
				$data['all_students'] = $this->Student_model->get_all_students();

                $data['_view'] = 'assignmentfile/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The assignmentfile you are trying to edit does not exist.');
    } 

    /*
     * Deleting assignmentfile
     */
    function remove($fileID)
    {
        $assignmentfile = $this->Assignmentfile_model->get_assignmentfile($fileID);

        // check if the assignmentfile exists before trying to delete it
        if(isset($assignmentfile['fileID']))
        {
            $this->Assignmentfile_model->delete_assignmentfile($fileID);
            redirect('assignmentfile/index');
        }
        else
            show_error('The assignmentfile you are trying to delete does not exist.');
    }
}
