<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Assignmentreply extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model(['Assignmentreply_model','Notification_model']);
    } 

    /*
     * Listing of assignmentreply
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('assignmentreply/index?');
        $config['total_rows'] = $this->Assignmentreply_model->get_all_assignmentreply_count();
        $this->pagination->initialize($config);

        $data['assignmentreply'] = $this->Assignmentreply_model->get_all_assignmentreply($params);
        
        $data['_view'] = 'assignmentreply/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new assignmentreply
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'moduleID' => $this->input->post('moduleID'),
				'assignmentID' => $this->input->post('assignmentID'),
				'studentID' => $this->input->post('studentID'),
				'assignmentRef' => $this->input->post('assignmentRef'),
				'reply' => $this->input->post('reply'),
				'deleteStatus' => $this->input->post('deleteStatus'),
				'time_stamp' => $this->input->post('time_stamp'),
            );
            
            $assignmentreply_id = $this->Assignmentreply_model->add_assignmentreply($params);
            redirect('assignmentreply/index');
        }
        else
        {
			$this->load->model('Module_model');
			$data['all_modules'] = $this->Module_model->get_all_modules();

			$this->load->model('Assignment_model');
			$data['all_assignment'] = $this->Assignment_model->get_all_assignment();

			$this->load->model('Student_model');
			$data['all_students'] = $this->Student_model->get_all_students();
            
            $data['_view'] = 'assignmentreply/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a assignmentreply
     */
    function edit($id)
    {   
        // check if the assignmentreply exists before trying to edit it
        $data['assignmentreply'] = $this->Assignmentreply_model->get_assignmentreply($id);
        
        if(isset($data['assignmentreply']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'moduleID' => $this->input->post('moduleID'),
					'assignmentID' => $this->input->post('assignmentID'),
					'studentID' => $this->input->post('studentID'),
					'assignmentRef' => $this->input->post('assignmentRef'),
					'reply' => $this->input->post('reply'),
					'deleteStatus' => $this->input->post('deleteStatus'),
					'time_stamp' => $this->input->post('time_stamp'),
                );

                $this->Assignmentreply_model->update_assignmentreply($id,$params);            
                redirect('assignmentreply/index');
            }
            else
            {
				$this->load->model('Module_model');
				$data['all_modules'] = $this->Module_model->get_all_modules();

				$this->load->model('Assignment_model');
				$data['all_assignment'] = $this->Assignment_model->get_all_assignment();

				$this->load->model('Student_model');
				$data['all_students'] = $this->Student_model->get_all_students();

                $data['_view'] = 'assignmentreply/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The assignmentreply you are trying to edit does not exist.');
    } 

    /*
     * Deleting assignmentreply
     */
    function remove($id)
    {
        $assignmentreply = $this->Assignmentreply_model->get_assignmentreply($id);

        // check if the assignmentreply exists before trying to delete it
        if(isset($assignmentreply['id']))
        {
            $this->Assignmentreply_model->delete_assignmentreply($id);
            redirect('assignmentreply/index');
        }
        else
            show_error('The assignmentreply you are trying to delete does not exist.');
    }
}
