<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Curriculum extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model(['Curriculum_model','Notification_model']);
    } 

    /*
     * Listing of curriculum
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('curriculum/index?');
        $config['total_rows'] = $this->Curriculum_model->get_all_curriculum_count();
        $this->pagination->initialize($config);

        $data['curriculum'] = $this->Curriculum_model->get_all_curriculum($params);
        
        $data['_view'] = 'curriculum/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new curriculum
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('curriculum','Curriculum','required|max_length[250]');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'courseID' => $this->input->post('courseID'),
				'curriculum' => $this->input->post('curriculum'),
				'deleteStatus' => $this->input->post('deleteStatus'),
				'time_stamp' => $this->input->post('time_stamp'),
            );
            
            $curriculum_id = $this->Curriculum_model->add_curriculum($params);
            redirect('curriculum/index');
        }
        else
        {
			$this->load->model('Course_model');
			$data['all_courses'] = $this->Course_model->get_all_courses();
            
            $data['_view'] = 'curriculum/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a curriculum
     */
    function edit($id)
    {   
        // check if the curriculum exists before trying to edit it
        $data['curriculum'] = $this->Curriculum_model->get_curriculum($id);
        
        if(isset($data['curriculum']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('curriculum','Curriculum','required|max_length[250]');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'courseID' => $this->input->post('courseID'),
					'curriculum' => $this->input->post('curriculum'),
					'deleteStatus' => $this->input->post('deleteStatus'),
					'time_stamp' => $this->input->post('time_stamp'),
                );

                $this->Curriculum_model->update_curriculum($id,$params);            
                redirect('curriculum/index');
            }
            else
            {
				$this->load->model('Course_model');
				$data['all_courses'] = $this->Course_model->get_all_courses();

                $data['_view'] = 'curriculum/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The curriculum you are trying to edit does not exist.');
    } 

    /*
     * Deleting curriculum
     */
    function remove($id)
    {
        $curriculum = $this->Curriculum_model->get_curriculum($id);

        // check if the curriculum exists before trying to delete it
        if(isset($curriculum['id']))
        {
            $this->Curriculum_model->delete_curriculum($id);
            redirect('curriculum/index');
        }
        else
            show_error('The curriculum you are trying to delete does not exist.');
    }

}
