<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Examfeedback extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model(['Examfeedback_model','Notification_model']);
    } 

    /*
     * Listing of examfeedback
     */
    function index()
    {
        $data['examfeedback'] = $this->Examfeedback_model->get_all_examfeedback();
        
        $data['_view'] = 'examfeedback/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new examfeedback
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'moduleID' => $this->input->post('moduleID'),
				'examID' => $this->input->post('examID'),
				'studentID' => $this->input->post('studentID'),
				'courseManager' => $this->input->post('courseManager'),
				'feedback' => $this->input->post('feedback'),
				'feedback2' => $this->input->post('feedback2'),
				'feedback3' => $this->input->post('feedback3'),
				'grade' => $this->input->post('grade'),
				'marks' => $this->input->post('marks'),
				'paper' => $this->input->post('paper'),
				'status' => $this->input->post('status'),
				'time_stamp' => $this->input->post('time_stamp'),
            );
            
            $examfeedback_id = $this->Examfeedback_model->add_examfeedback($params);
            redirect('examfeedback/index');
        }
        else
        {            
            $data['_view'] = 'examfeedback/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a examfeedback
     */
    function edit($id)
    {   
        // check if the examfeedback exists before trying to edit it
        $data['examfeedback'] = $this->Examfeedback_model->get_examfeedback($id);
        
        if(isset($data['examfeedback']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'moduleID' => $this->input->post('moduleID'),
					'examID' => $this->input->post('examID'),
					'studentID' => $this->input->post('studentID'),
					'courseManager' => $this->input->post('courseManager'),
					'feedback' => $this->input->post('feedback'),
					'feedback2' => $this->input->post('feedback2'),
					'feedback3' => $this->input->post('feedback3'),
					'grade' => $this->input->post('grade'),
					'marks' => $this->input->post('marks'),
					'paper' => $this->input->post('paper'),
					'status' => $this->input->post('status'),
					'time_stamp' => $this->input->post('time_stamp'),
                );

                $this->Examfeedback_model->update_examfeedback($id,$params);            
                redirect('examfeedback/index');
            }
            else
            {
                $data['_view'] = 'examfeedback/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The examfeedback you are trying to edit does not exist.');
    } 

    /*
     * Deleting examfeedback
     */
    function remove($id)
    {
        $examfeedback = $this->Examfeedback_model->get_examfeedback($id);

        // check if the examfeedback exists before trying to delete it
        if(isset($examfeedback['id']))
        {
            $this->Examfeedback_model->delete_examfeedback($id);
            redirect('examfeedback/index');
        }
        else
            show_error('The examfeedback you are trying to delete does not exist.');
    }
}
