<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Examreply extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model(['Examreply_model','Notification_model']);
    } 

    /*
     * Listing of examreply
     */
    function index()
    {
        $data['examreply'] = $this->Examreply_model->get_all_examreply();
        
        $data['_view'] = 'examreply/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new examreply
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'courseID' => $this->input->post('courseID'),
				'moduleID' => $this->input->post('moduleID'),
				'examID' => $this->input->post('examID'),
				'exam' => $this->input->post('exam'),
				'paper' => $this->input->post('paper'),
				'studentID' => $this->input->post('studentID'),
				'deleteStatus' => $this->input->post('deleteStatus'),
				'time_stamp' => $this->input->post('time_stamp'),
            );
            
            $examreply_id = $this->Examreply_model->add_examreply($params);
            redirect('examreply/index');
        }
        else
        {            
            $data['_view'] = 'examreply/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a examreply
     */
    function edit($id)
    {   
        // check if the examreply exists before trying to edit it
        $data['examreply'] = $this->Examreply_model->get_examreply($id);
        
        if(isset($data['examreply']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'courseID' => $this->input->post('courseID'),
					'moduleID' => $this->input->post('moduleID'),
					'examID' => $this->input->post('examID'),
					'exam' => $this->input->post('exam'),
					'paper' => $this->input->post('paper'),
					'studentID' => $this->input->post('studentID'),
					'deleteStatus' => $this->input->post('deleteStatus'),
					'time_stamp' => $this->input->post('time_stamp'),
                );

                $this->Examreply_model->update_examreply($id,$params);            
                redirect('examreply/index');
            }
            else
            {
                $data['_view'] = 'examreply/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The examreply you are trying to edit does not exist.');
    } 

    /*
     * Deleting examreply
     */
    function remove($id)
    {
        $examreply = $this->Examreply_model->get_examreply($id);

        // check if the examreply exists before trying to delete it
        if(isset($examreply['id']))
        {
            $this->Examreply_model->delete_examreply($id);
            redirect('examreply/index');
        }
        else
            show_error('The examreply you are trying to delete does not exist.');
    }

}
