<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Extralesson extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model(['Extralesson_model','Notification_model']);
    } 

    /*
     * Listing of extralessons
     */
    function index()
    {
        $data['extralessons'] = $this->Extralesson_model->get_all_extralessons();
        
        $data['_view'] = 'extralesson/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new extralesson
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'subjectID' => $this->input->post('subjectID'),
				'tutorID' => $this->input->post('tutorID'),
				'lessonName' => $this->input->post('lessonName'),
				'weekDay' => $this->input->post('weekDay'),
				'roomID' => $this->input->post('roomID'),
				'roomPin' => $this->input->post('roomPin'),
				'adminPin' => $this->input->post('adminPin'),
				'price' => $this->input->post('price'),
				'grade' => $this->input->post('grade'),
				'lessonTime' => $this->input->post('lessonTime'),
				'lessonDate' => $this->input->post('lessonDate'),
				'lessonStart' => $this->input->post('lessonStart'),
				'lessonEnd' => $this->input->post('lessonEnd'),
				'ref' => $this->input->post('ref'),
				'dateEventCreated' => $this->input->post('dateEventCreated'),
				'lessonDescription' => $this->input->post('lessonDescription'),
            );
            
            $extralesson_id = $this->Extralesson_model->add_extralesson($params);
            redirect('extralesson/index');
        }
        else
        {            
            $data['_view'] = 'extralesson/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a extralesson
     */
    function edit($lessonID)
    {   
        // check if the extralesson exists before trying to edit it
        $data['extralesson'] = $this->Extralesson_model->get_extralesson($lessonID);
        
        if(isset($data['extralesson']['lessonID']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'subjectID' => $this->input->post('subjectID'),
					'tutorID' => $this->input->post('tutorID'),
					'lessonName' => $this->input->post('lessonName'),
					'weekDay' => $this->input->post('weekDay'),
					'roomID' => $this->input->post('roomID'),
					'roomPin' => $this->input->post('roomPin'),
					'adminPin' => $this->input->post('adminPin'),
					'price' => $this->input->post('price'),
					'grade' => $this->input->post('grade'),
					'lessonTime' => $this->input->post('lessonTime'),
					'lessonDate' => $this->input->post('lessonDate'),
					'lessonStart' => $this->input->post('lessonStart'),
					'lessonEnd' => $this->input->post('lessonEnd'),
					'ref' => $this->input->post('ref'),
					'dateEventCreated' => $this->input->post('dateEventCreated'),
					'lessonDescription' => $this->input->post('lessonDescription'),
                );

                $this->Extralesson_model->update_extralesson($lessonID,$params);            
                redirect('extralesson/index');
            }
            else
            {
                $data['_view'] = 'extralesson/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The extralesson you are trying to edit does not exist.');
    } 

    /*
     * Deleting extralesson
     */
    function remove($lessonID)
    {
        $extralesson = $this->Extralesson_model->get_extralesson($lessonID);

        // check if the extralesson exists before trying to delete it
        if(isset($extralesson['lessonID']))
        {
            $this->Extralesson_model->delete_extralesson($lessonID);
            redirect('extralesson/index');
        }
        else
            show_error('The extralesson you are trying to delete does not exist.');
    }

}
