<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Feedback extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model(['Feedback_model','Notification_model']);
    } 

    /*
     * Listing of feedback
     */
    function index()
    {
        $data['feedback'] = $this->Feedback_model->get_all_feedback();
        
        $data['_view'] = 'feedback/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new feedback
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'facilitatorID' => $this->input->post('facilitatorID'),
				'moduleID' => $this->input->post('moduleID'),
				'marks' => $this->input->post('marks'),
				'topicID' => $this->input->post('topicID'),
				'studentID' => $this->input->post('studentID'),
				'feedback' => $this->input->post('feedback'),
				'feedbackType' => $this->input->post('feedbackType'),
				'time_stamp' => $this->input->post('time_stamp'),
				'feedback2' => $this->input->post('feedback2'),
            );
            
            $feedback_id = $this->Feedback_model->add_feedback($params);
            redirect('feedback/index');
        }
        else
        {            
            $data['_view'] = 'feedback/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a feedback
     */
    function edit($id)
    {   
        // check if the feedback exists before trying to edit it
        $data['feedback'] = $this->Feedback_model->get_feedback($id);
        
        if(isset($data['feedback']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'facilitatorID' => $this->input->post('facilitatorID'),
					'moduleID' => $this->input->post('moduleID'),
					'marks' => $this->input->post('marks'),
					'topicID' => $this->input->post('topicID'),
					'studentID' => $this->input->post('studentID'),
					'feedback' => $this->input->post('feedback'),
					'feedbackType' => $this->input->post('feedbackType'),
					'time_stamp' => $this->input->post('time_stamp'),
					'feedback2' => $this->input->post('feedback2'),
                );

                $this->Feedback_model->update_feedback($id,$params);            
                redirect('feedback/index');
            }
            else
            {
                $data['_view'] = 'feedback/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The feedback you are trying to edit does not exist.');
    } 

    /*
     * Deleting feedback
     */
    function remove($id)
    {
        $feedback = $this->Feedback_model->get_feedback($id);

        // check if the feedback exists before trying to delete it
        if(isset($feedback['id']))
        {
            $this->Feedback_model->delete_feedback($id);
            redirect('feedback/index');
        }
        else
            show_error('The feedback you are trying to delete does not exist.');
    }

}
