<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Groupdiscus extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model(['Groupdiscus_model','Student_model','Management_model','Topic_model']);
    } 

    /*
     * Listing of groupdiscuss
     */
    function index()
    {
        $data['groupdiscuss'] = $this->Groupdiscus_model->get_all_groupdiscuss();
        
        $data['_view'] = 'groupdiscus/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new groupdiscus
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'topicID' => $this->input->post('topicID'),
				'studentID' => $this->input->post('studentID'),
				'facilitatorID' => $this->input->post('facilitatorID'),
				'chapter' => $this->input->post('chapter'),
				'moduleID' => $this->input->post('moduleID'),
				'time_stamp' => $this->input->post('time_stamp'),
				'discussion' => $this->input->post('discussion'),
				'discussion2' => $this->input->post('discussion2'),
            );
            
            $groupdiscus_id = $this->Groupdiscus_model->add_groupdiscus($params);
            redirect('groupdiscus/index');
        }
        else
        {            
            $data['_view'] = 'groupdiscus/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a groupdiscus
     */
    function edit($id)
    {   
        // check if the groupdiscus exists before trying to edit it
        $data['groupdiscus'] = $this->Groupdiscus_model->get_groupdiscus($id);
        
        if(isset($data['groupdiscus']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'topicID' => $this->input->post('topicID'),
					'studentID' => $this->input->post('studentID'),
					'facilitatorID' => $this->input->post('facilitatorID'),
					'chapter' => $this->input->post('chapter'),
					'moduleID' => $this->input->post('moduleID'),
					'time_stamp' => $this->input->post('time_stamp'),
					'discussion' => $this->input->post('discussion'),
					'discussion2' => $this->input->post('discussion2'),
                );

                $this->Groupdiscus_model->update_groupdiscus($id,$params);            
                redirect('groupdiscus/index');
            }
            else
            {
                $data['_view'] = 'groupdiscus/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The groupdiscus you are trying to edit does not exist.');
    } 

    /*
     * Deleting groupdiscus
     */
    function remove($id)
    {
        $groupdiscus = $this->Groupdiscus_model->get_groupdiscus($id);

        // check if the groupdiscus exists before trying to delete it
        if(isset($groupdiscus['id']))
        {
            $this->Groupdiscus_model->delete_groupdiscus($id);
            redirect('groupdiscus/index');
        }
        else
            show_error('The groupdiscus you are trying to delete does not exist.');
    }

    function openChat($topic)
    {
        $groupdiscus = $this->Groupdiscus_model->get_groupdiscus_by_topic($topic);
        $topicGet = $this->Topic_model->get_topic($topic);

        if(isset($groupdiscus))
        {
            $data['discussions'] = $groupdiscus;
            $data['students'] = $this->Student_model->get_all_students();
            $data['profs'] = $this->Management_model->get_all_management();
            $data['topic'] = $topic;
            $data['module'] = $topicGet['moduleID'];
            $this->load->view('header_footer/header_admin');
            $this->load->view('groupdiscus/discus',$data);
            $this->load->view('header_footer/footer_admin');
        }
        else
            show_error('The groupdiscus you are trying to delete does not exist.');

    }

    function sendMessage(){

        $params = array(
            'topicID' => $this->input->post('topicID'),
            'studentID' => $this->input->post('studentID'),
            'moduleID' => $this->input->post('moduleID'),
            'time_stamp' => $this->input->post('time_stamp'),
            'discussion2' => $this->input->post('discussion2'),
        );

        $groupdiscus_id = $this->Groupdiscus_model->add_groupdiscus($params);
        redirect('groupdiscus/openChat/'.$this->input->post('topicID'));
    }

    function sendMessageProf(){

        $params = array(
            'topicID' => $this->input->post('topicID'),
            'studentID' => $this->input->post('studentID'),
            'moduleID' => $this->input->post('moduleID'),
            'time_stamp' => $this->input->post('time_stamp'),
            'discussion' => $this->input->post('discussion'),
        );

        $groupdiscus_id = $this->Groupdiscus_model->add_groupdiscus($params);
        redirect('groupdiscus/openChat/'.$this->input->post('topicID'));
    }
    
}
