<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Lectureassign extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Lectureassign_model');
    } 

    /*
     * Listing of lectureassigns
     */
    function index()
    {
        $data['lectureassigns'] = $this->Lectureassign_model->get_all_lectureassigns();
        
        $data['_view'] = 'lectureassign/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new lectureassign
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'lectureID' => $this->input->post('lectureID'),
				'moduleID' => $this->input->post('moduleID'),
				'time_stamp' => $this->input->post('time_stamp'),
            );
            
            $lectureassign_id = $this->Lectureassign_model->add_lectureassign($params);
            redirect('lectureassign/index');
        }
        else
        {            
            $data['_view'] = 'lectureassign/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a lectureassign
     */
    function edit($AssigneeID)
    {   
        // check if the lectureassign exists before trying to edit it
        $data['lectureassign'] = $this->Lectureassign_model->get_lectureassign($AssigneeID);
        
        if(isset($data['lectureassign']['AssigneeID']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'lectureID' => $this->input->post('lectureID'),
					'moduleID' => $this->input->post('moduleID'),
					'time_stamp' => $this->input->post('time_stamp'),
                );

                $this->Lectureassign_model->update_lectureassign($AssigneeID,$params);            
                redirect('lectureassign/index');
            }
            else
            {
                $data['_view'] = 'lectureassign/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The lectureassign you are trying to edit does not exist.');
    } 

    /*
     * Deleting lectureassign
     */
    function remove($AssigneeID)
    {
        $lectureassign = $this->Lectureassign_model->get_lectureassign($AssigneeID);

        // check if the lectureassign exists before trying to delete it
        if(isset($lectureassign['AssigneeID']))
        {
            $this->Lectureassign_model->delete_lectureassign($AssigneeID);
            redirect('lectureassign/index');
        }
        else
            show_error('The lectureassign you are trying to delete does not exist.');
    }
    
}
