<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Lecturerroom extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Lecturerroom_model');
    } 

    /*
     * Listing of lecturerroom
     */
    function index()
    {
        $data['lecturerroom'] = $this->Lecturerroom_model->get_all_lecturerroom();
        
        $data['_view'] = 'lecturerroom/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new lecturerroom
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'departmentID' => $this->input->post('departmentID'),
				'name' => $this->input->post('name'),
				'dateCreated' => $this->input->post('dateCreated'),
            );
            
            $lecturerroom_id = $this->Lecturerroom_model->add_lecturerroom($params);
            redirect('lecturerroom/index');
        }
        else
        {            
            $data['_view'] = 'lecturerroom/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a lecturerroom
     */
    function edit($ID)
    {   
        // check if the lecturerroom exists before trying to edit it
        $data['lecturerroom'] = $this->Lecturerroom_model->get_lecturerroom($ID);
        
        if(isset($data['lecturerroom']['ID']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'departmentID' => $this->input->post('departmentID'),
					'name' => $this->input->post('name'),
					'dateCreated' => $this->input->post('dateCreated'),
                );

                $this->Lecturerroom_model->update_lecturerroom($ID,$params);            
                redirect('lecturerroom/index');
            }
            else
            {
                $data['_view'] = 'lecturerroom/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The lecturerroom you are trying to edit does not exist.');
    } 

    /*
     * Deleting lecturerroom
     */
    function remove($ID)
    {
        $lecturerroom = $this->Lecturerroom_model->get_lecturerroom($ID);

        // check if the lecturerroom exists before trying to delete it
        if(isset($lecturerroom['ID']))
        {
            $this->Lecturerroom_model->delete_lecturerroom($ID);
            redirect('lecturerroom/index');
        }
        else
            show_error('The lecturerroom you are trying to delete does not exist.');
    }
    
}
