<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Lessontopic extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Lessontopic_model');
    } 

    /*
     * Listing of lessontopic
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('lessontopic/index?');
        $config['total_rows'] = $this->Lessontopic_model->get_all_lessontopic_count();
        $this->pagination->initialize($config);

        $data['lessontopic'] = $this->Lessontopic_model->get_all_lessontopic($params);
        
        $data['_view'] = 'lessontopic/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new lessontopic
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('topicName','TopicName','required');
		$this->form_validation->set_rules('topicAssignment','TopicAssignment','required');
		$this->form_validation->set_rules('lessonTopicStatus','LessonTopicStatus','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'moduleID' => $this->input->post('moduleID'),
				'topicName' => $this->input->post('topicName'),
				'topicAssignment' => $this->input->post('topicAssignment'),
				'lessonTopicStatus' => $this->input->post('lessonTopicStatus'),
				'time_stamp' => $this->input->post('time_stamp'),
            );
            
            $lessontopic_id = $this->Lessontopic_model->add_lessontopic($params);
            redirect('lessontopic/index');
        }
        else
        {
			$this->load->model('Module_model');
			$data['all_modules'] = $this->Module_model->get_all_modules();
            
            $data['_view'] = 'lessontopic/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a lessontopic
     */
    function edit($topicID)
    {   
        // check if the lessontopic exists before trying to edit it
        $data['lessontopic'] = $this->Lessontopic_model->get_lessontopic($topicID);
        
        if(isset($data['lessontopic']['topicID']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('topicName','TopicName','required');
			$this->form_validation->set_rules('topicAssignment','TopicAssignment','required');
			$this->form_validation->set_rules('lessonTopicStatus','LessonTopicStatus','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'moduleID' => $this->input->post('moduleID'),
					'topicName' => $this->input->post('topicName'),
					'topicAssignment' => $this->input->post('topicAssignment'),
					'lessonTopicStatus' => $this->input->post('lessonTopicStatus'),
					'time_stamp' => $this->input->post('time_stamp'),
                );

                $this->Lessontopic_model->update_lessontopic($topicID,$params);            
                redirect('lessontopic/index');
            }
            else
            {
				$this->load->model('Module_model');
				$data['all_modules'] = $this->Module_model->get_all_modules();

                $data['_view'] = 'lessontopic/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The lessontopic you are trying to edit does not exist.');
    } 

    /*
     * Deleting lessontopic
     */
    function remove($topicID)
    {
        $lessontopic = $this->Lessontopic_model->get_lessontopic($topicID);

        // check if the lessontopic exists before trying to delete it
        if(isset($lessontopic['topicID']))
        {
            $this->Lessontopic_model->delete_lessontopic($topicID);
            redirect('lessontopic/index');
        }
        else
            show_error('The lessontopic you are trying to delete does not exist.');
    }
    
}
