<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Login extends CI_Controller
{
    public function __construct(){

        parent::__construct();
		$this->load->model(['Management_model', "Student_model", "Department_model"]);
    }

    /*
     * Listing of lessontopic
     */
    public function index(){

        $this->form_validation->set_rules('email','email','required|max_length[200]');
		$this->form_validation->set_rules('password','password','required|max_length[20]');

		if($this->form_validation->run()) {

			$email = $this->input->post('email');
			$password = $this->input->post('password');
			$admin = $this->Management_model->auth_management($email,$password);
			$student = $this->Student_model->auth_student($email,$password);
			$departement = $this->Department_model->auth_departement($email,$password);

			if(count($student)>0){
				
				$this->session->set_userdata([
					"id_user"=>$student[0]->studentID,
					'name_user'=>$student[0]->studentLastName,
					"activate_status"=>$student[0]->activeStatus,
					'type_user'=>2,
					'status'=>TRUE,
				]);

				redirect('student/my_courses');
			}
			elseif(count($admin)>0){
				
				$this->session->set_userdata([
					"id_user"=>$admin[0]->managementID,
					'name_user'=>$admin[0]->lastName,
					'type_user'=>1,
					'status'=>TRUE,
				]);

				redirect('course/report');
			}
			elseif(count($departement)>0){
				
				$this->session->set_userdata([
					"id_user"=>$departement[0]->departmentID,
					'name_user'=>$departement[0]->departmentName,
					'type_user'=>3,
					'status'=>TRUE,
				]);

				redirect('dashboard/index');
			}
			else{

				$this->session->set_flashdata('error', TRUE);
				redirect($_SERVER['HTTP_REFERER']);
			}
			
		} else {
			$this->load->view('login/index');
		}
    }
	function deconnexion(){
		session_destroy();
		redirect(site_url());
	}
}