<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Moduleassign extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Moduleassign_model');
    } 

    /*
     * Listing of moduleassign
     */
    function index()
    {
        $data['moduleassign'] = $this->Moduleassign_model->get_all_moduleassign();
        
        $data['_view'] = 'moduleassign/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new moduleassign
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'moduleID' => $this->input->post('moduleID'),
				'courseID' => $this->input->post('courseID'),
				'studentID' => $this->input->post('studentID'),
				'time_stamp' => $this->input->post('time_stamp'),
            );
            
            $moduleassign_id = $this->Moduleassign_model->add_moduleassign($params);
            redirect('moduleassign/index');
        }
        else
        {            
            $data['_view'] = 'moduleassign/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a moduleassign
     */
    function edit($id)
    {   
        // check if the moduleassign exists before trying to edit it
        $data['moduleassign'] = $this->Moduleassign_model->get_moduleassign($id);
        
        if(isset($data['moduleassign']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'moduleID' => $this->input->post('moduleID'),
					'courseID' => $this->input->post('courseID'),
					'studentID' => $this->input->post('studentID'),
					'time_stamp' => $this->input->post('time_stamp'),
                );

                $this->Moduleassign_model->update_moduleassign($id,$params);            
                redirect('moduleassign/index');
            }
            else
            {
                $data['_view'] = 'moduleassign/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The moduleassign you are trying to edit does not exist.');
    } 

    /*
     * Deleting moduleassign
     */
    function remove($id)
    {
        $moduleassign = $this->Moduleassign_model->get_moduleassign($id);

        // check if the moduleassign exists before trying to delete it
        if(isset($moduleassign['id']))
        {
            $this->Moduleassign_model->delete_moduleassign($id);
            redirect('moduleassign/index');
        }
        else
            show_error('The moduleassign you are trying to delete does not exist.');
    }
    
}
