<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Modulematerial extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Modulematerial_model');
    } 

    /*
     * Listing of modulematerial
     */
    function index()
    {
        $data['modulematerial'] = $this->Modulematerial_model->get_all_modulematerial();
        
        $data['_view'] = 'modulematerial/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new modulematerial
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'moduleName' => $this->input->post('moduleName'),
				'moduleFile' => $this->input->post('moduleFile'),
				'userID' => $this->input->post('userID'),
				'topicName' => $this->input->post('topicName'),
				'deleteStatus' => $this->input->post('deleteStatus'),
				'time_stamp' => $this->input->post('time_stamp'),
            );
            
            $modulematerial_id = $this->Modulematerial_model->add_modulematerial($params);
            redirect('modulematerial/index');
        }
        else
        {            
            $data['_view'] = 'modulematerial/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a modulematerial
     */
    function edit($moduleID)
    {   
        // check if the modulematerial exists before trying to edit it
        $data['modulematerial'] = $this->Modulematerial_model->get_modulematerial($moduleID);
        
        if(isset($data['modulematerial']['moduleID']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'moduleName' => $this->input->post('moduleName'),
					'moduleFile' => $this->input->post('moduleFile'),
					'userID' => $this->input->post('userID'),
					'topicName' => $this->input->post('topicName'),
					'deleteStatus' => $this->input->post('deleteStatus'),
					'time_stamp' => $this->input->post('time_stamp'),
                );

                $this->Modulematerial_model->update_modulematerial($moduleID,$params);            
                redirect('modulematerial/index');
            }
            else
            {
                $data['_view'] = 'modulematerial/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The modulematerial you are trying to edit does not exist.');
    } 

    /*
     * Deleting modulematerial
     */
    function remove($moduleID)
    {
        $modulematerial = $this->Modulematerial_model->get_modulematerial($moduleID);

        // check if the modulematerial exists before trying to delete it
        if(isset($modulematerial['moduleID']))
        {
            $this->Modulematerial_model->delete_modulematerial($moduleID);
            redirect('modulematerial/index');
        }
        else
            show_error('The modulematerial you are trying to delete does not exist.');
    }
    
}
