<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Parentinfo extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Parentinfo_model');
    } 

    /*
     * Listing of parentinfo
     */
    function index()
    {
        $data['parentinfo'] = $this->Parentinfo_model->get_all_parentinfo();
        
        $data['_view'] = 'parentinfo/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new parentinfo
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'studentID' => $this->input->post('studentID'),
				'kinName' => $this->input->post('kinName'),
				'relationship' => $this->input->post('relationship'),
				'kinPhone' => $this->input->post('kinPhone'),
				'kinCellPhone' => $this->input->post('kinCellPhone'),
				'kinAddress' => $this->input->post('kinAddress'),
				'schoolName' => $this->input->post('schoolName'),
				'qualification' => $this->input->post('qualification'),
				'year' => $this->input->post('year'),
				'courseEnd' => $this->input->post('courseEnd'),
				'dateCreated' => $this->input->post('dateCreated'),
            );
            
            $parentinfo_id = $this->Parentinfo_model->add_parentinfo($params);
            redirect('parentinfo/index');
        }
        else
        {            
            $data['_view'] = 'parentinfo/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a parentinfo
     */
    function edit($parentID)
    {   
        // check if the parentinfo exists before trying to edit it
        $data['parentinfo'] = $this->Parentinfo_model->get_parentinfo($parentID);
        
        if(isset($data['parentinfo']['parentID']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'studentID' => $this->input->post('studentID'),
					'kinName' => $this->input->post('kinName'),
					'relationship' => $this->input->post('relationship'),
					'kinPhone' => $this->input->post('kinPhone'),
					'kinCellPhone' => $this->input->post('kinCellPhone'),
					'kinAddress' => $this->input->post('kinAddress'),
					'schoolName' => $this->input->post('schoolName'),
					'qualification' => $this->input->post('qualification'),
					'year' => $this->input->post('year'),
					'courseEnd' => $this->input->post('courseEnd'),
					'dateCreated' => $this->input->post('dateCreated'),
                );

                $this->Parentinfo_model->update_parentinfo($parentID,$params);            
                redirect('parentinfo/index');
            }
            else
            {
                $data['_view'] = 'parentinfo/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The parentinfo you are trying to edit does not exist.');
    } 

    /*
     * Deleting parentinfo
     */
    function remove($parentID)
    {
        $parentinfo = $this->Parentinfo_model->get_parentinfo($parentID);

        // check if the parentinfo exists before trying to delete it
        if(isset($parentinfo['parentID']))
        {
            $this->Parentinfo_model->delete_parentinfo($parentID);
            redirect('parentinfo/index');
        }
        else
            show_error('The parentinfo you are trying to delete does not exist.');
    }
    
}
