<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Reply extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Reply_model');
    } 

    /*
     * Listing of reply
     */
    function index()
    {
        $data['reply'] = $this->Reply_model->get_all_reply();
        
        $data['_view'] = 'reply/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new reply
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'studentID' => $this->input->post('studentID'),
				'facilitatorID' => $this->input->post('facilitatorID'),
				'discussionID' => $this->input->post('discussionID'),
				'topicID' => $this->input->post('topicID'),
				'moduleID' => $this->input->post('moduleID'),
				'marks' => $this->input->post('marks'),
				'reply' => $this->input->post('reply'),
				'fileType' => $this->input->post('fileType'),
				'time_stamp' => $this->input->post('time_stamp'),
				'reply2' => $this->input->post('reply2'),
            );
            
            $reply_id = $this->Reply_model->add_reply($params);
            redirect('reply/index');
        }
        else
        {            
            $data['_view'] = 'reply/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a reply
     */
    function edit($id)
    {   
        // check if the reply exists before trying to edit it
        $data['reply'] = $this->Reply_model->get_reply($id);
        
        if(isset($data['reply']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'studentID' => $this->input->post('studentID'),
					'facilitatorID' => $this->input->post('facilitatorID'),
					'discussionID' => $this->input->post('discussionID'),
					'topicID' => $this->input->post('topicID'),
					'moduleID' => $this->input->post('moduleID'),
					'marks' => $this->input->post('marks'),
					'reply' => $this->input->post('reply'),
					'fileType' => $this->input->post('fileType'),
					'time_stamp' => $this->input->post('time_stamp'),
					'reply2' => $this->input->post('reply2'),
                );

                $this->Reply_model->update_reply($id,$params);            
                redirect('reply/index');
            }
            else
            {
                $data['_view'] = 'reply/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The reply you are trying to edit does not exist.');
    } 

    /*
     * Deleting reply
     */
    function remove($id)
    {
        $reply = $this->Reply_model->get_reply($id);

        // check if the reply exists before trying to delete it
        if(isset($reply['id']))
        {
            $this->Reply_model->delete_reply($id);
            redirect('reply/index');
        }
        else
            show_error('The reply you are trying to delete does not exist.');
    }
    
}
