<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Stafffunction extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Stafffunction_model');
    } 

    /*
     * Listing of stafffunction
     */
    function index()
    {
        $data['stafffunction'] = $this->Stafffunction_model->get_all_stafffunction();
        
        $data['_view'] = 'stafffunction/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new stafffunction
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'staffFunction' => $this->input->post('staffFunction'),
				'time_stamp' => $this->input->post('time_stamp'),
            );
            
            $stafffunction_id = $this->Stafffunction_model->add_stafffunction($params);
            redirect('stafffunction/index');
        }
        else
        {            
            $data['_view'] = 'stafffunction/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a stafffunction
     */
    function edit($id)
    {   
        // check if the stafffunction exists before trying to edit it
        $data['stafffunction'] = $this->Stafffunction_model->get_stafffunction($id);
        
        if(isset($data['stafffunction']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'staffFunction' => $this->input->post('staffFunction'),
					'time_stamp' => $this->input->post('time_stamp'),
                );

                $this->Stafffunction_model->update_stafffunction($id,$params);            
                redirect('stafffunction/index');
            }
            else
            {
                $data['_view'] = 'stafffunction/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The stafffunction you are trying to edit does not exist.');
    } 

    /*
     * Deleting stafffunction
     */
    function remove($id)
    {
        $stafffunction = $this->Stafffunction_model->get_stafffunction($id);

        // check if the stafffunction exists before trying to delete it
        if(isset($stafffunction['id']))
        {
            $this->Stafffunction_model->delete_stafffunction($id);
            redirect('stafffunction/index');
        }
        else
            show_error('The stafffunction you are trying to delete does not exist.');
    }
    
}
