<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Teacherfile extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Teacherfile_model');
    } 

    /*
     * Listing of teacherfiles
     */
    function index()
    {
        $data['teacherfiles'] = $this->Teacherfile_model->get_all_teacherfiles();
        
        $data['_view'] = 'teacherfile/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new teacherfile
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'assignmentID' => $this->input->post('assignmentID'),
				'lectureID' => $this->input->post('lectureID'),
				'file' => $this->input->post('file'),
				'deleteStatus' => $this->input->post('deleteStatus'),
				'time_stamp' => $this->input->post('time_stamp'),
            );
            
            $teacherfile_id = $this->Teacherfile_model->add_teacherfile($params);
            redirect('teacherfile/index');
        }
        else
        {            
            $data['_view'] = 'teacherfile/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a teacherfile
     */
    function edit($fileID)
    {   
        // check if the teacherfile exists before trying to edit it
        $data['teacherfile'] = $this->Teacherfile_model->get_teacherfile($fileID);
        
        if(isset($data['teacherfile']['fileID']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'assignmentID' => $this->input->post('assignmentID'),
					'lectureID' => $this->input->post('lectureID'),
					'file' => $this->input->post('file'),
					'deleteStatus' => $this->input->post('deleteStatus'),
					'time_stamp' => $this->input->post('time_stamp'),
                );

                $this->Teacherfile_model->update_teacherfile($fileID,$params);            
                redirect('teacherfile/index');
            }
            else
            {
                $data['_view'] = 'teacherfile/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The teacherfile you are trying to edit does not exist.');
    } 

    /*
     * Deleting teacherfile
     */
    function remove($fileID)
    {
        $teacherfile = $this->Teacherfile_model->get_teacherfile($fileID);

        // check if the teacherfile exists before trying to delete it
        if(isset($teacherfile['fileID']))
        {
            $this->Teacherfile_model->delete_teacherfile($fileID);
            redirect('teacherfile/index');
        }
        else
            show_error('The teacherfile you are trying to delete does not exist.');
    }
    
}
