<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Topic extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Topic_model');
    } 

    /*
     * Listing of topics
     */
    function index()
    {
        $data['topics'] = $this->Topic_model->get_all_topics();
        
        $data['_view'] = 'topic/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new topic
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'moduleID' => $this->input->post('moduleID'),
				'topicName' => $this->input->post('topicName'),
				'extra' => $this->input->post('extra'),
				'deleteStatus' => $this->input->post('deleteStatus'),
				'status' => $this->input->post('status'),
				'time_stamp' => $this->input->post('time_stamp'),
            );
            
            $topic_id = $this->Topic_model->add_topic($params);
            redirect('topic/index');
        }
        else
        {            
            $data['_view'] = 'topic/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a topic
     */
    function edit($id)
    {   
        // check if the topic exists before trying to edit it
        $data['topic'] = $this->Topic_model->get_topic($id);
        
        if(isset($data['topic']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'moduleID' => $this->input->post('moduleID'),
					'topicName' => $this->input->post('topicName'),
					'extra' => $this->input->post('extra'),
					'deleteStatus' => $this->input->post('deleteStatus'),
					'status' => $this->input->post('status'),
					'time_stamp' => $this->input->post('time_stamp'),
                );

                $this->Topic_model->update_topic($id,$params);            
                redirect('topic/index');
            }
            else
            {
                $data['_view'] = 'topic/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The topic you are trying to edit does not exist.');
    } 

    /*
     * Deleting topic
     */
    function remove($id)
    {
        $topic = $this->Topic_model->get_topic($id);

        // check if the topic exists before trying to delete it
        if(isset($topic['id']))
        {
            $this->Topic_model->delete_topic($id);
            redirect('topic/index');
        }
        else
            show_error('The topic you are trying to delete does not exist.');
    }
    
}
