<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Userlog extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Userlog_model');
    } 

    /*
     * Listing of userlog
     */
    function index()
    {
        $data['userlog'] = $this->Userlog_model->get_all_userlog();
        
        $data['_view'] = 'userlog/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new userlog
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'logID' => $this->input->post('logID'),
				'userType' => $this->input->post('userType'),
				'userIP' => $this->input->post('userIP'),
				'loginTime' => $this->input->post('loginTime'),
            );
            
            $userlog_id = $this->Userlog_model->add_userlog($params);
            redirect('userlog/index');
        }
        else
        {            
            $data['_view'] = 'userlog/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a userlog
     */
    function edit($userID)
    {   
        // check if the userlog exists before trying to edit it
        $data['userlog'] = $this->Userlog_model->get_userlog($userID);
        
        if(isset($data['userlog']['userID']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'logID' => $this->input->post('logID'),
					'userType' => $this->input->post('userType'),
					'userIP' => $this->input->post('userIP'),
					'loginTime' => $this->input->post('loginTime'),
                );

                $this->Userlog_model->update_userlog($userID,$params);            
                redirect('userlog/index');
            }
            else
            {
                $data['_view'] = 'userlog/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The userlog you are trying to edit does not exist.');
    } 

    /*
     * Deleting userlog
     */
    function remove($userID)
    {
        $userlog = $this->Userlog_model->get_userlog($userID);

        // check if the userlog exists before trying to delete it
        if(isset($userlog['userID']))
        {
            $this->Userlog_model->delete_userlog($userID);
            redirect('userlog/index');
        }
        else
            show_error('The userlog you are trying to delete does not exist.');
    }
    
}
