<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Viewednotification extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Viewednotification_model');
    } 

    /*
     * Listing of viewednotification
     */
    function index()
    {
        $data['viewednotification'] = $this->Viewednotification_model->get_all_viewednotification();
        
        $data['_view'] = 'viewednotification/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new viewednotification
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'userID' => $this->input->post('userID'),
				'userType' => $this->input->post('userType'),
				'notificationID' => $this->input->post('notificationID'),
				'dateViewed' => $this->input->post('dateViewed'),
            );
            
            $viewednotification_id = $this->Viewednotification_model->add_viewednotification($params);
            redirect('viewednotification/index');
        }
        else
        {            
            $data['_view'] = 'viewednotification/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a viewednotification
     */
    function edit($id)
    {   
        // check if the viewednotification exists before trying to edit it
        $data['viewednotification'] = $this->Viewednotification_model->get_viewednotification($id);
        
        if(isset($data['viewednotification']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'userID' => $this->input->post('userID'),
					'userType' => $this->input->post('userType'),
					'notificationID' => $this->input->post('notificationID'),
					'dateViewed' => $this->input->post('dateViewed'),
                );

                $this->Viewednotification_model->update_viewednotification($id,$params);            
                redirect('viewednotification/index');
            }
            else
            {
                $data['_view'] = 'viewednotification/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The viewednotification you are trying to edit does not exist.');
    } 

    /*
     * Deleting viewednotification
     */
    function remove($id)
    {
        $viewednotification = $this->Viewednotification_model->get_viewednotification($id);

        // check if the viewednotification exists before trying to delete it
        if(isset($viewednotification['id']))
        {
            $this->Viewednotification_model->delete_viewednotification($id);
            redirect('viewednotification/index');
        }
        else
            show_error('The viewednotification you are trying to delete does not exist.');
    }
    
}
