-- Generated by CRUDigniter v2.3 Beta 
-- www.crudigniter.com

-- Generation Time: Sep 22, 2021 12:45 PM

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Table structure for table `assignedcourses`
--

DROP TABLE IF EXISTS `assignedcourses`;
CREATE TABLE `assignedcourses` (
`courseAssignedID` int(11) NOT NULL,
`courseID` int(11) NOT NULL,
`studentID` int(11) NOT NULL,
`timestamp` timestamp NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Indexes for table `assignedcourses`
--

ALTER TABLE `assignedcourses`
ADD PRIMARY KEY (`courseAssignedID`);

--
-- AUTO_INCREMENT for table `assignedcourses`
--

ALTER TABLE `assignedcourses`
MODIFY `courseAssignedID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

-- --------------------------------------------------------

--
-- Table structure for table `assignment`
--

DROP TABLE IF EXISTS `assignment`;
CREATE TABLE `assignment` (
`id` int(11) NOT NULL,
`assignment` varchar(255) NOT NULL,
`assignmentNo` varchar(255) NOT NULL,
`marks` varchar(255) NOT NULL,
`topicName` varchar(255) NOT NULL,
`comment` longtext NOT NULL,
`dueDate` varchar(255) NOT NULL,
`moduleID` varchar(255) NOT NULL,
`facilitatorID` varchar(255) NOT NULL,
`deleteStatus` varchar(255) NOT NULL,
`time_stamp` timestamp NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Indexes for table `assignment`
--

ALTER TABLE `assignment`
ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for table `assignment`
--

ALTER TABLE `assignment`
MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

-- --------------------------------------------------------

--
-- Table structure for table `assignmentfeedback`
--

DROP TABLE IF EXISTS `assignmentfeedback`;
CREATE TABLE `assignmentfeedback` (
`id` int(11) NOT NULL,
`studentID` int(255) NOT NULL,
`adminID` int(255) NOT NULL,
`feedback` varchar(255) NOT NULL,
`assignmentID` int(255) NOT NULL,
`moduleID` int(255) NOT NULL,
`total` varchar(255) NOT NULL,
`grade` varchar(255) NOT NULL,
`status` varchar(255) NOT NULL,
`comment` varchar(255) NOT NULL,
`time_stamp` timestamp NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Indexes for table `assignmentfeedback`
--

ALTER TABLE `assignmentfeedback`
ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for table `assignmentfeedback`
--

ALTER TABLE `assignmentfeedback`
MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

-- --------------------------------------------------------

--
-- Table structure for table `assignmentfiles`
--

DROP TABLE IF EXISTS `assignmentfiles`;
CREATE TABLE `assignmentfiles` (
`fileID` int(11) NOT NULL,
`assignmentID` int(255) NOT NULL,
`studentID` int(255) NOT NULL,
`file` varchar(255) NOT NULL,
`deleteStatus` int(11) NOT NULL,
`time_stamp` timestamp NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Indexes for table `assignmentfiles`
--

ALTER TABLE `assignmentfiles`
ADD PRIMARY KEY (`fileID`);

--
-- AUTO_INCREMENT for table `assignmentfiles`
--

ALTER TABLE `assignmentfiles`
MODIFY `fileID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

-- --------------------------------------------------------

--
-- Table structure for table `assignmentreply`
--

DROP TABLE IF EXISTS `assignmentreply`;
CREATE TABLE `assignmentreply` (
`id` int(11) NOT NULL,
`moduleID` int(255) NOT NULL,
`assignmentID` int(255) NOT NULL,
`assignmentRef` varchar(255) NOT NULL,
`reply` varchar(255) NOT NULL,
`studentID` int(255) NOT NULL,
`deleteStatus` varchar(255) NOT NULL,
`time_stamp` timestamp NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Indexes for table `assignmentreply`
--

ALTER TABLE `assignmentreply`
ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for table `assignmentreply`
--

ALTER TABLE `assignmentreply`
MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

-- --------------------------------------------------------

--
-- Table structure for table `cart`
--

DROP TABLE IF EXISTS `cart`;
CREATE TABLE `cart` (
`cartID` int(11) NOT NULL,
`userID` int(255) NOT NULL,
`moduleID` int(255) NOT NULL,
`time_stamp` timestamp NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Indexes for table `cart`
--

ALTER TABLE `cart`
ADD PRIMARY KEY (`cartID`);

--
-- AUTO_INCREMENT for table `cart`
--

ALTER TABLE `cart`
MODIFY `cartID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

-- --------------------------------------------------------

--
-- Table structure for table `classroom`
--

DROP TABLE IF EXISTS `classroom`;
CREATE TABLE `classroom` (
`Id` int(11) NOT NULL,
`roomID` varchar(255) NOT NULL,
`roomOTP` varchar(255) NOT NULL,
`roomName` varchar(255) NOT NULL,
`roomPin` varchar(255) NOT NULL,
`userID` varchar(255) NOT NULL,
`studentPin` varchar(255) NOT NULL,
`scheduledDate` varchar(255) NOT NULL,
`startTime` varchar(255) NOT NULL,
`endTime` varchar(255) NOT NULL,
`status` varchar(255) NOT NULL,
`time_stamp` timestamp NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Indexes for table `classroom`
--

ALTER TABLE `classroom`
ADD PRIMARY KEY (`Id`);

--
-- AUTO_INCREMENT for table `classroom`
--

ALTER TABLE `classroom`
MODIFY `Id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

-- --------------------------------------------------------

--
-- Table structure for table `community`
--

DROP TABLE IF EXISTS `community`;
CREATE TABLE `community` (
`id` int(11) NOT NULL,
`studentID` int(255) NOT NULL,
`facilitatorID` int(255) NOT NULL,
`moduleID` int(255) NOT NULL,
`discussion` varchar(255) NOT NULL,
`discussion2` varchar(255) NOT NULL,
`time_stamp` timestamp NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Indexes for table `community`
--

ALTER TABLE `community`
ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for table `community`
--

ALTER TABLE `community`
MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

-- --------------------------------------------------------

--
-- Table structure for table `courses`
--

DROP TABLE IF EXISTS `courses`;
CREATE TABLE `courses` (
`coursesID` int(11) NOT NULL,
`courseName` varchar(50) NOT NULL,
`courseType` varchar(60) NOT NULL,
`courseDepartment` varchar(255) NOT NULL,
`curriculum` varchar(255) ,
`courseManager` varchar(10) ,
`courseCode` varchar(20) ,
`courseDuration` int(11) ,
`courseTimeline` varchar(60) ,
`courseLevel` varchar(60) ,
`courseCredits` int(11) ,
`coursePrice` double ,
`courseOverview` mediumtext ,
`courseIntake` varchar(10) ,
`courseDelivery` varchar(100) ,
`courseStartDate` varchar(255) ,
`time_stamp` timestamp 
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Indexes for table `courses`
--

ALTER TABLE `courses`
ADD PRIMARY KEY (`coursesID`);

--
-- AUTO_INCREMENT for table `courses`
--

ALTER TABLE `courses`
MODIFY `coursesID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

-- --------------------------------------------------------

--
-- Table structure for table `curriculum`
--

DROP TABLE IF EXISTS `curriculum`;
CREATE TABLE `curriculum` (
`id` int(11) NOT NULL,
`curriculum` varchar(255) NOT NULL,
`courseID` int(255) NOT NULL,
`deleteStatus` varchar(255) NOT NULL,
`time_stamp` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Indexes for table `curriculum`
--

ALTER TABLE `curriculum`
ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for table `curriculum`
--

ALTER TABLE `curriculum`
MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

-- --------------------------------------------------------

--
-- Table structure for table `department`
--

DROP TABLE IF EXISTS `department`;
CREATE TABLE `department` (
`departmentID` int(11) NOT NULL,
`departmentName` varchar(255) NOT NULL,
`hodID` int(255) NOT NULL,
`time_stamp` timestamp NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Indexes for table `department`
--

ALTER TABLE `department`
ADD PRIMARY KEY (`departmentID`);

--
-- AUTO_INCREMENT for table `department`
--

ALTER TABLE `department`
MODIFY `departmentID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

-- --------------------------------------------------------

--
-- Table structure for table `discussion`
--

DROP TABLE IF EXISTS `discussion`;
CREATE TABLE `discussion` (
`discussionID` int(11) NOT NULL,
`discussion` longtext NOT NULL,
`discussion2` longtext NOT NULL,
`instruction` varchar(255) NOT NULL,
`dueDate` varchar(255) NOT NULL,
`topicID` int(255) NOT NULL,
`moduleID` int(255) NOT NULL,
`studentID` int(255) NOT NULL,
`facilitatorID` int(255) NOT NULL,
`facilitatorID2` int(255) NOT NULL,
`academicID` int(255) NOT NULL,
`time_stamp` timestamp NOT NULL,
`marks` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Indexes for table `discussion`
--

ALTER TABLE `discussion`
ADD PRIMARY KEY (`discussionID`);

--
-- AUTO_INCREMENT for table `discussion`
--

ALTER TABLE `discussion`
MODIFY `discussionID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

-- --------------------------------------------------------

--
-- Table structure for table `events`
--

DROP TABLE IF EXISTS `events`;
CREATE TABLE `events` (
`eventID` int(11) NOT NULL,
`eventTitle` varchar(50) NOT NULL,
`eventDate` date NOT NULL,
`eventstatTime` time NOT NULL,
`eventendTime` time NOT NULL,
`eventLocation` varchar(20) NOT NULL,
`eventDescription` varchar(500) NOT NULL,
`eventType` int(11) NOT NULL,
`eventImage` varchar(260) NOT NULL,
`eventStatus` int(11) NOT NULL,
`eventTimestamp` timestamp NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Indexes for table `events`
--

ALTER TABLE `events`
ADD PRIMARY KEY (`eventID`);

--
-- AUTO_INCREMENT for table `events`
--

ALTER TABLE `events`
MODIFY `eventID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

-- --------------------------------------------------------

--
-- Table structure for table `events_table`
--

DROP TABLE IF EXISTS `events_table`;
CREATE TABLE `events_table` (
`id` int(11) NOT NULL,
`title` varchar(50) ,
`className` varchar(50) ,
`start` datetime ,
`end` datetime ,
`details` varchar(255) ,
`created_at` timestamp 
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Indexes for table `events_table`
--

ALTER TABLE `events_table`
ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for table `events_table`
--

ALTER TABLE `events_table`
MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

-- --------------------------------------------------------

--
-- Table structure for table `exam`
--

DROP TABLE IF EXISTS `exam`;
CREATE TABLE `exam` (
`id` int(11) NOT NULL,
`moduleID` int(255) NOT NULL,
`date` date NOT NULL,
`start` time NOT NULL,
`end` time NOT NULL,
`title` varchar(255) NOT NULL,
`exam` varchar(255) NOT NULL,
`marks` varchar(255) NOT NULL,
`term` varchar(255) NOT NULL,
`paper` varchar(255) NOT NULL,
`deleteStatus` varchar(255) NOT NULL,
`time_stamp` timestamp NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Indexes for table `exam`
--

ALTER TABLE `exam`
ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for table `exam`
--

ALTER TABLE `exam`
MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

-- --------------------------------------------------------

--
-- Table structure for table `examanswer`
--

DROP TABLE IF EXISTS `examanswer`;
CREATE TABLE `examanswer` (
`answerID` int(11) NOT NULL,
`moduleID` int(255) NOT NULL,
`examName` longtext NOT NULL,
`answer` varchar(255) NOT NULL,
`activeStatus` int(11) NOT NULL,
`time_stamp` timestamp NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Indexes for table `examanswer`
--

ALTER TABLE `examanswer`
ADD PRIMARY KEY (`answerID`);

--
-- AUTO_INCREMENT for table `examanswer`
--

ALTER TABLE `examanswer`
MODIFY `answerID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

-- --------------------------------------------------------

--
-- Table structure for table `examfeedback`
--

DROP TABLE IF EXISTS `examfeedback`;
CREATE TABLE `examfeedback` (
`id` int(11) NOT NULL,
`moduleID` int(255) NOT NULL,
`examID` int(255) NOT NULL,
`studentID` int(255) NOT NULL,
`courseManager` varchar(255) NOT NULL,
`feedback` varchar(255) NOT NULL,
`feedback2` varchar(255) NOT NULL,
`feedback3` varchar(255) NOT NULL,
`grade` varchar(255) NOT NULL,
`marks` varchar(255) NOT NULL,
`paper` varchar(255) NOT NULL,
`status` varchar(255) NOT NULL,
`time_stamp` timestamp NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Indexes for table `examfeedback`
--

ALTER TABLE `examfeedback`
ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for table `examfeedback`
--

ALTER TABLE `examfeedback`
MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

-- --------------------------------------------------------

--
-- Table structure for table `examreply`
--

DROP TABLE IF EXISTS `examreply`;
CREATE TABLE `examreply` (
`id` int(11) NOT NULL,
`courseID` int(255) NOT NULL,
`moduleID` int(255) NOT NULL,
`examID` int(255) NOT NULL,
`exam` varchar(255) NOT NULL,
`paper` varchar(255) NOT NULL,
`studentID` int(255) NOT NULL,
`deleteStatus` varchar(255) NOT NULL,
`time_stamp` timestamp NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Indexes for table `examreply`
--

ALTER TABLE `examreply`
ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for table `examreply`
--

ALTER TABLE `examreply`
MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

-- --------------------------------------------------------

--
-- Table structure for table `extralessons`
--

DROP TABLE IF EXISTS `extralessons`;
CREATE TABLE `extralessons` (
`lessonID` int(11) NOT NULL,
`subjectID` int(11) NOT NULL,
`tutorID` int(11) NOT NULL,
`lessonName` varchar(255) NOT NULL,
`weekDay` varchar(255) NOT NULL,
`roomID` varchar(255) NOT NULL,
`roomPin` varchar(255) NOT NULL,
`adminPin` varchar(255) NOT NULL,
`price` int(11) NOT NULL,
`grade` int(11) NOT NULL,
`lessonTime` varchar(255) NOT NULL,
`lessonDate` varchar(255) NOT NULL,
`lessonStart` varchar(255) NOT NULL,
`lessonEnd` varchar(255) NOT NULL,
`lessonDescription` longtext NOT NULL,
`ref` varchar(255) NOT NULL,
`dateEventCreated` timestamp NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Indexes for table `extralessons`
--

ALTER TABLE `extralessons`
ADD PRIMARY KEY (`lessonID`);

--
-- AUTO_INCREMENT for table `extralessons`
--

ALTER TABLE `extralessons`
MODIFY `lessonID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

-- --------------------------------------------------------

--
-- Table structure for table `feedback`
--

DROP TABLE IF EXISTS `feedback`;
CREATE TABLE `feedback` (
`id` int(11) NOT NULL,
`facilitatorID` int(255) NOT NULL,
`moduleID` int(255) NOT NULL,
`marks` varchar(255) NOT NULL,
`topicID` varchar(255) NOT NULL,
`studentID` int(255) NOT NULL,
`feedback` varchar(255) NOT NULL,
`feedback2` longtext NOT NULL,
`feedbackType` varchar(255) NOT NULL,
`time_stamp` timestamp NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Indexes for table `feedback`
--

ALTER TABLE `feedback`
ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for table `feedback`
--

ALTER TABLE `feedback`
MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

-- --------------------------------------------------------

--
-- Table structure for table `groupdiscuss`
--

DROP TABLE IF EXISTS `groupdiscuss`;
CREATE TABLE `groupdiscuss` (
`id` int(11) NOT NULL,
`topicID` int(255) NOT NULL,
`studentID` int(255) NOT NULL,
`facilitatorID` int(255) NOT NULL,
`chapter` varchar(255) NOT NULL,
`moduleID` int(255) NOT NULL,
`discussion` longtext NOT NULL,
`discussion2` longtext NOT NULL,
`time_stamp` timestamp NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Indexes for table `groupdiscuss`
--

ALTER TABLE `groupdiscuss`
ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for table `groupdiscuss`
--

ALTER TABLE `groupdiscuss`
MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

-- --------------------------------------------------------

--
-- Table structure for table `learning`
--

DROP TABLE IF EXISTS `learning`;
CREATE TABLE `learning` (
`learningID` int(11) NOT NULL,
`learningName` longtext NOT NULL,
`learningTopic` varchar(255) NOT NULL,
`moduleID` int(255) NOT NULL,
`time_stamp` timestamp NOT NULL,
`comment` longtext NOT NULL,
`link` longtext NOT NULL,
`deleteStatus` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Indexes for table `learning`
--

ALTER TABLE `learning`
ADD PRIMARY KEY (`learningID`);

--
-- AUTO_INCREMENT for table `learning`
--

ALTER TABLE `learning`
MODIFY `learningID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

-- --------------------------------------------------------

--
-- Table structure for table `learningmaterial`
--

DROP TABLE IF EXISTS `learningmaterial`;
CREATE TABLE `learningmaterial` (
`materialID` int(11) NOT NULL,
`file` varchar(255) NOT NULL,
`learningID` int(255) NOT NULL,
`deleteStatus` int(11) NOT NULL,
`time_stamp` timestamp NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Indexes for table `learningmaterial`
--

ALTER TABLE `learningmaterial`
ADD PRIMARY KEY (`materialID`);

--
-- AUTO_INCREMENT for table `learningmaterial`
--

ALTER TABLE `learningmaterial`
MODIFY `materialID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

-- --------------------------------------------------------

--
-- Table structure for table `lectureassigns`
--

DROP TABLE IF EXISTS `lectureassigns`;
CREATE TABLE `lectureassigns` (
`AssigneeID` int(11) NOT NULL,
`lectureID` int(11) NOT NULL,
`moduleID` int(11) NOT NULL,
`time_stamp` timestamp NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Indexes for table `lectureassigns`
--

ALTER TABLE `lectureassigns`
ADD PRIMARY KEY (`AssigneeID`);

--
-- AUTO_INCREMENT for table `lectureassigns`
--

ALTER TABLE `lectureassigns`
MODIFY `AssigneeID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

-- --------------------------------------------------------

--
-- Table structure for table `lecturerroom`
--

DROP TABLE IF EXISTS `lecturerroom`;
CREATE TABLE `lecturerroom` (
`ID` int(10) unsigned NOT NULL,
`departmentID` int(10) unsigned NOT NULL,
`name` varchar(255) NOT NULL,
`dateCreated` datetime NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Indexes for table `lecturerroom`
--

ALTER TABLE `lecturerroom`
ADD PRIMARY KEY (`ID`);

--
-- AUTO_INCREMENT for table `lecturerroom`
--

ALTER TABLE `lecturerroom`
MODIFY `ID` int(10) unsigned NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

-- --------------------------------------------------------

--
-- Table structure for table `lessons`
--

DROP TABLE IF EXISTS `lessons`;
CREATE TABLE `lessons` (
`lessonID` int(11) NOT NULL,
`subjectID` int(11) NOT NULL,
`tutorID` int(11) NOT NULL,
`lessonName` varchar(255) NOT NULL,
`weekDay` varchar(255) NOT NULL,
`roomID` varchar(255) NOT NULL,
`roomPin` varchar(255) NOT NULL,
`adminPin` varchar(255) NOT NULL,
`lecturerRoomID` int(10) unsigned NOT NULL,
`grade` int(11) NOT NULL,
`lessonTime` varchar(255) NOT NULL,
`lessonDate` varchar(255) NOT NULL,
`lessonStart` varchar(255) NOT NULL,
`lessonEnd` varchar(255) NOT NULL,
`lessonDescription` longtext NOT NULL,
`ref` varchar(255) NOT NULL,
`dateEventCreated` timestamp NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Indexes for table `lessons`
--

ALTER TABLE `lessons`
ADD PRIMARY KEY (`lessonID`);

--
-- AUTO_INCREMENT for table `lessons`
--

ALTER TABLE `lessons`
MODIFY `lessonID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

-- --------------------------------------------------------

--
-- Table structure for table `lessontopic`
--

DROP TABLE IF EXISTS `lessontopic`;
CREATE TABLE `lessontopic` (
`topicID` int(11) NOT NULL,
`topicName` varchar(50) NOT NULL,
`moduleID` int(11) NOT NULL,
`topicAssignment` varchar(250) NOT NULL,
`lessonTopicStatus` int(3) NOT NULL,
`time_stamp` timestamp NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Indexes for table `lessontopic`
--

ALTER TABLE `lessontopic`
ADD PRIMARY KEY (`topicID`);

--
-- AUTO_INCREMENT for table `lessontopic`
--

ALTER TABLE `lessontopic`
MODIFY `topicID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

-- --------------------------------------------------------

--
-- Table structure for table `management`
--

DROP TABLE IF EXISTS `management`;
CREATE TABLE `management` (
`managementID` int(11) NOT NULL,
`managementName` varchar(100) NOT NULL,
`lastName` varchar(255) NOT NULL,
`title` varchar(255) NOT NULL,
`managementEmail` varchar(100) NOT NULL,
`managementContact` varchar(20) NOT NULL,
`managementPassword` varchar(250) NOT NULL,
`managementPhoto` varchar(250) NOT NULL,
`managementLevel` varchar(255) NOT NULL,
`otp` varchar(255) NOT NULL,
`address` varchar(255) NOT NULL,
`securityAns` varchar(100) NOT NULL,
`managementBio` longtext NOT NULL,
`managementStatus` int(11) NOT NULL,
`gender` varchar(255) NOT NULL,
`programme` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Indexes for table `management`
--

ALTER TABLE `management`
ADD PRIMARY KEY (`managementID`);

--
-- AUTO_INCREMENT for table `management`
--

ALTER TABLE `management`
MODIFY `managementID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

-- --------------------------------------------------------

--
-- Table structure for table `moduleassign`
--

DROP TABLE IF EXISTS `moduleassign`;
CREATE TABLE `moduleassign` (
`id` int(11) NOT NULL,
`moduleID` int(255) NOT NULL,
`courseID` int(255) NOT NULL,
`studentID` int(255) NOT NULL,
`time_stamp` timestamp NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Indexes for table `moduleassign`
--

ALTER TABLE `moduleassign`
ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for table `moduleassign`
--

ALTER TABLE `moduleassign`
MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

-- --------------------------------------------------------

--
-- Table structure for table `modulematerial`
--

DROP TABLE IF EXISTS `modulematerial`;
CREATE TABLE `modulematerial` (
`moduleID` int(11) NOT NULL,
`moduleName` varchar(255) NOT NULL,
`moduleFile` varchar(255) NOT NULL,
`userID` int(255) NOT NULL,
`topicName` varchar(255) NOT NULL,
`deleteStatus` int(11) NOT NULL,
`time_stamp` timestamp NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Indexes for table `modulematerial`
--

ALTER TABLE `modulematerial`
ADD PRIMARY KEY (`moduleID`);

--
-- AUTO_INCREMENT for table `modulematerial`
--

ALTER TABLE `modulematerial`
MODIFY `moduleID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

-- --------------------------------------------------------

--
-- Table structure for table `modules`
--

DROP TABLE IF EXISTS `modules`;
CREATE TABLE `modules` (
`moduleID` int(11) NOT NULL,
`moduleName` varchar(50) NOT NULL,
`moduleType` varchar(30) NOT NULL,
`moduleCourseID` int(11) NOT NULL,
`moduleLevel` varchar(255) NOT NULL,
`moduleOverview` longtext NOT NULL,
`moduleCredit` int(11) NOT NULL,
`moduleDuration` varchar(255) NOT NULL,
`modulePeriod` varchar(255) NOT NULL,
`modulePrerequisites` varchar(255) NOT NULL,
`moduleEligible` varchar(255) NOT NULL,
`modulePrice` varchar(255) NOT NULL,
`moduleCode` varchar(10) NOT NULL,
`moduleFile` varchar(250) NOT NULL,
`moduleDate` datetime NOT NULL,
`id` int(255) 
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Indexes for table `modules`
--

ALTER TABLE `modules`
ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for table `modules`
--

ALTER TABLE `modules`
MODIFY `id` int(255) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

-- --------------------------------------------------------

--
-- Table structure for table `notification`
--

DROP TABLE IF EXISTS `notification`;
CREATE TABLE `notification` (
`id` int(11) NOT NULL,
`title` varchar(255) NOT NULL,
`notification` longtext NOT NULL,
`adminID` varchar(255) NOT NULL,
`viewed` int(11) NOT NULL,
`viewedBy` int(11) NOT NULL,
`time_stamp` timestamp NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Indexes for table `notification`
--

ALTER TABLE `notification`
ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for table `notification`
--

ALTER TABLE `notification`
MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

-- --------------------------------------------------------

--
-- Table structure for table `parentinfo`
--

DROP TABLE IF EXISTS `parentinfo`;
CREATE TABLE `parentinfo` (
`parentID` int(11) NOT NULL,
`studentID` int(11) NOT NULL,
`kinName` varchar(255) ,
`relationship` varchar(255) ,
`kinPhone` varchar(255) ,
`kinCellPhone` varchar(255) ,
`kinAddress` varchar(255) ,
`schoolName` varchar(255) ,
`qualification` varchar(255) ,
`year` varchar(20) ,
`courseEnd` varchar(60) ,
`dateCreated` datetime 
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Indexes for table `parentinfo`
--

ALTER TABLE `parentinfo`
ADD PRIMARY KEY (`parentID`);

--
-- AUTO_INCREMENT for table `parentinfo`
--

ALTER TABLE `parentinfo`
MODIFY `parentID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

-- --------------------------------------------------------

--
-- Table structure for table `reply`
--

DROP TABLE IF EXISTS `reply`;
CREATE TABLE `reply` (
`id` int(11) NOT NULL,
`studentID` int(255) NOT NULL,
`facilitatorID` int(255) NOT NULL,
`discussionID` varchar(255) NOT NULL,
`topicID` int(255) NOT NULL,
`moduleID` int(255) NOT NULL,
`marks` varchar(255) NOT NULL,
`reply` varchar(255) NOT NULL,
`reply2` longtext NOT NULL,
`fileType` varchar(255) NOT NULL,
`time_stamp` timestamp NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Indexes for table `reply`
--

ALTER TABLE `reply`
ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for table `reply`
--

ALTER TABLE `reply`
MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

-- --------------------------------------------------------

--
-- Table structure for table `stafffunction`
--

DROP TABLE IF EXISTS `stafffunction`;
CREATE TABLE `stafffunction` (
`id` int(11) NOT NULL,
`staffFunction` varchar(255) NOT NULL,
`time_stamp` timestamp NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Indexes for table `stafffunction`
--

ALTER TABLE `stafffunction`
ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for table `stafffunction`
--

ALTER TABLE `stafffunction`
MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

-- --------------------------------------------------------

--
-- Table structure for table `students`
--

DROP TABLE IF EXISTS `students`;
CREATE TABLE `students` (
`studentID` int(11) NOT NULL,
`studentName` varchar(50) NOT NULL,
`studentLastName` varchar(255) ,
`studentDOB` date ,
`studentCountry` varchar(255) ,
`studentNumber` varchar(255) ,
`number` int(11) NOT NULL,
`identityNo` varchar(255) ,
`gender` varchar(255) ,
`studentEmail` varchar(100) ,
`studentPassword` varchar(400) ,
`studentPhone` varchar(20) ,
`studentHomeNo` varchar(20) ,
`studentImage` varchar(250) ,
`studentAddress` varchar(250) ,
`passport` varchar(30) ,
`disability` tinyint(4) ,
`hearing` tinyint(4) ,
`physicalHealth` tinyint(4) ,
`intellectual` tinyint(4) ,
`learning` tinyint(4) ,
`mental` tinyint(4) ,
`vision` tinyint(4) ,
`medical` tinyint(4) ,
`other` varchar(255) ,
`aggrement` longtext ,
`passportDOC` varchar(255) ,
`proofOfPayment` varchar(255) ,
`certificates` varchar(255) ,
`otp` int(11) ,
`activeStatus` int(11) ,
`studentTimestamp` timestamp ,
`year` year(4) NOT NULL,
`studentMiddleName` varchar(255) 
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Indexes for table `students`
--

ALTER TABLE `students`
ADD PRIMARY KEY (`studentID`);

--
-- AUTO_INCREMENT for table `students`
--

ALTER TABLE `students`
MODIFY `studentID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

-- --------------------------------------------------------

--
-- Table structure for table `teacherfiles`
--

DROP TABLE IF EXISTS `teacherfiles`;
CREATE TABLE `teacherfiles` (
`fileID` int(11) NOT NULL,
`assignmentID` varchar(255) NOT NULL,
`lectureID` varchar(255) NOT NULL,
`file` varchar(255) NOT NULL,
`deleteStatus` int(11) NOT NULL,
`time_stamp` timestamp NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Indexes for table `teacherfiles`
--

ALTER TABLE `teacherfiles`
ADD PRIMARY KEY (`fileID`);

--
-- AUTO_INCREMENT for table `teacherfiles`
--

ALTER TABLE `teacherfiles`
MODIFY `fileID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

-- --------------------------------------------------------

--
-- Table structure for table `timetable`
--

DROP TABLE IF EXISTS `timetable`;
CREATE TABLE `timetable` (
`id` int(11) NOT NULL,
`courseID` int(255) NOT NULL,
`examRoom` varchar(255) NOT NULL,
`examTime` varchar(255) NOT NULL,
`paper` varchar(255) NOT NULL,
`exam_date` varchar(255) NOT NULL,
`time_stamp` timestamp NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Indexes for table `timetable`
--

ALTER TABLE `timetable`
ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for table `timetable`
--

ALTER TABLE `timetable`
MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

-- --------------------------------------------------------

--
-- Table structure for table `topics`
--

DROP TABLE IF EXISTS `topics`;
CREATE TABLE `topics` (
`id` int(11) NOT NULL,
`moduleID` int(255) NOT NULL,
`topicName` varchar(255) NOT NULL,
`extra` varchar(255) NOT NULL,
`deleteStatus` int(11) NOT NULL,
`status` varchar(255) NOT NULL,
`time_stamp` timestamp NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Indexes for table `topics`
--

ALTER TABLE `topics`
ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for table `topics`
--

ALTER TABLE `topics`
MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

-- --------------------------------------------------------

--
-- Table structure for table `userlog`
--

DROP TABLE IF EXISTS `userlog`;
CREATE TABLE `userlog` (
`logID` int(11) unsigned NOT NULL,
`userID` int(11) unsigned NOT NULL,
`userType` varchar(255) NOT NULL,
`userIP` varbinary(16) NOT NULL,
`loginTime` datetime NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Indexes for table `userlog`
--

ALTER TABLE `userlog`
ADD PRIMARY KEY (`userID`);

--
-- AUTO_INCREMENT for table `userlog`
--

ALTER TABLE `userlog`
MODIFY `userID` int(11) unsigned NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
`ID` int(11) NOT NULL,
`username` varchar(255) NOT NULL,
`password` varchar(55) NOT NULL,
`email` varchar(255) NOT NULL,
`phone` int(11) NOT NULL,
`type` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Indexes for table `users`
--

ALTER TABLE `users`
ADD PRIMARY KEY (`ID`);

--
-- AUTO_INCREMENT for table `users`
--

ALTER TABLE `users`
MODIFY `ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

-- --------------------------------------------------------

--
-- Table structure for table `viewednotification`
--

DROP TABLE IF EXISTS `viewednotification`;
CREATE TABLE `viewednotification` (
`id` int(11) NOT NULL,
`userID` int(11) NOT NULL,
`userType` varchar(20) NOT NULL,
`notificationID` int(11) NOT NULL,
`dateViewed` datetime NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Indexes for table `viewednotification`
--

ALTER TABLE `viewednotification`
ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for table `viewednotification`
--

ALTER TABLE `viewednotification`
MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

-- --------------------------------------------------------


/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
