<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Assignmentfile_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get assignmentfile by fileID
     */
    function get_assignmentfile($fileID)
    {
        return $this->db->get_where('assignmentfiles',array('fileID'=>$fileID))->row_array();
    }
    
    /*
     * Get all assignmentfiles count
     */
    function get_all_assignmentfiles_count()
    {
        $this->db->from('assignmentfiles');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all assignmentfiles
     */
    function get_all_assignmentfiles($params = array())
    {
        $this->db->order_by('fileID', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('assignmentfiles')->result_array();
    }
        
    /*
     * function to add new assignmentfile
     */
    function add_assignmentfile($params)
    {
        $this->db->insert('assignmentfiles',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update assignmentfile
     */
    function update_assignmentfile($fileID,$params)
    {
        $this->db->where('fileID',$fileID);
        return $this->db->update('assignmentfiles',$params);
    }
    
    /*
     * function to delete assignmentfile
     */
    function delete_assignmentfile($fileID)
    {
        return $this->db->delete('assignmentfiles',array('fileID'=>$fileID));
    }
}
