<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Assignmentfeedback_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get assignmentfeedback by id
     */
    function get_assignmentfeedback($id)
    {
        return $this->db->get_where('assignmentfeedback',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all assignmentfeedback count
     */
    function get_all_assignmentfeedback_count()
    {
        $this->db->from('assignmentfeedback');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all assignmentfeedback
     */
    function get_all_assignmentfeedback($params = array())
    {
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('assignmentfeedback')->result_array();
    }
        
    /*
     * function to add new assignmentfeedback
     */
    function add_assignmentfeedback($params)
    {
        $this->db->insert('assignmentfeedback',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update assignmentfeedback
     */
    function update_assignmentfeedback($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('assignmentfeedback',$params);
    }
    
    /*
     * function to delete assignmentfeedback
     */
    function delete_assignmentfeedback($id)
    {
        return $this->db->delete('assignmentfeedback',array('id'=>$id));
    }
}
