<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Assignmentreply_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get assignmentreply by id
     */
    function get_assignmentreply($id)
    {
        return $this->db->get_where('assignmentreply',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all assignmentreply count
     */
    function get_all_assignmentreply_count()
    {
        $this->db->from('assignmentreply');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all assignmentreply
     */
    function get_all_assignmentreply($params = array())
    {
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('assignmentreply')->result_array();
    }
        
    /*
     * function to add new assignmentreply
     */
    function add_assignmentreply($params)
    {
        $this->db->insert('assignmentreply',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update assignmentreply
     */
    function update_assignmentreply($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('assignmentreply',$params);
    }
    
    /*
     * function to delete assignmentreply
     */
    function delete_assignmentreply($id)
    {
        return $this->db->delete('assignmentreply',array('id'=>$id));
    }
}
