 <?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Assignedcourse_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get assignedcourse by courseAssignedID
     */
    function get_assignedcourse($courseAssignedID)
    {
        return $this->db->get_where('assignedcourses',array('courseAssignedID'=>$courseAssignedID))->row_array();
    }
    
    function get_students(){

        $this->db->select('*');
        $this->db->from('assignedCourses');
        $this->db->join('courses','courses.coursesID = assignedCourses.courseID');
        $this->db->join('students','students.studentID = assignedCourses.studentID');
        return $this->db->get()->result_array();
    }
    /*
     * Get all assignedcourses count
     */
    function get_all_assignedcourses_count()
    {
        $this->db->from('assignedCourses');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all assignedcourses
     */
    function get_all_assignedcourses($params = array())
    {
        $this->db->order_by('courseAssignedID', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('assignedCourses')->result_array();
    }
        
    /*
     * function to add new assignedcourse
     */
    function add_assignedcourse($params)
    {
        $this->db->insert('assignedCourses',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update assignedcourse
     */
    function update_assignedcourse($courseAssignedID,$params)
    {
        $this->db->where('courseAssignedID',$courseAssignedID);
        return $this->db->update('assignedCourses',$params);
    }
    
    /*
     * function to delete assignedcourse
     */
    function delete_assignedcourse($courseAssignedID)
    {
        return $this->db->delete('assignedCourses',array('courseAssignedID'=>$courseAssignedID));
    }
}
