<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Assignment_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get assignment by id
     */
    function get_assignment($id)
    {
        return $this->db->get_where('assignment',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all assignment count
     */
    function get_all_assignment_count()
    {
        $this->db->from('assignment');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all assignment
     */
    function get_all_assignment($params = array())
    {
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('assignment')->result_array();
    }
        
    /*
     * function to add new assignment
     */
    function add_assignment($params)
    {
        $this->db->insert('assignment',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update assignment
     */
    function update_assignment($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('assignment',$params);
    }
    
    /*
     * function to delete assignment
     */
    function delete_assignment($id)
    {
        return $this->db->delete('assignment',array('id'=>$id));
    }
}
