<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Book_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get assignmentreply by id
     */
    function get_book($id)
    {
        return $this->db->get_where('book',array('id_book'=>$id))->row_array();
    }
    
    /*
     * Get all assignmentreply count
     */
    function get_all_book_count()
    {
        $this->db->from('book');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all assignmentreply
     */
    function get_all_book($params = array())
    {
        $this->db->order_by('id_book', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('book')->result_array();
    }
        
    /*
     * function to add new assignmentreply
     */
    function add_book($params)
    {
        $this->db->insert('book',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update assignmentreply
     */
    function update_book($id,$params)
    {
        $this->db->where('id_book',$id);
        return $this->db->update('book',$params);
    }
    
    /*
     * function to delete assignmentreply
     */
    function delete_book($id)
    {
        return $this->db->delete('book',array('id_book'=>$id));
    }
}
