<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Classroom_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get classroom by Id
     */
    function get_classroom($Id)
    {
        return $this->db->get_where('classroom',array('Id'=>$Id))->row_array();
    }
    
    /*
     * Get all classroom count
     */
    function get_all_classroom_count()
    {
        $this->db->from('classroom');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all classroom
     */
    function get_all_classroom($params = array())
    {
        $this->db->order_by('Id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('classroom')->result_array();
    }
        
    /*
     * function to add new classroom
     */
    function add_classroom($params)
    {
        $this->db->insert('classroom',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update classroom
     */
    function update_classroom($Id,$params)
    {
        $this->db->where('Id',$Id);
        return $this->db->update('classroom',$params);
    }
    
    /*
     * function to delete classroom
     */
    function delete_classroom($Id)
    {
        return $this->db->delete('classroom',array('Id'=>$Id));
    }
}
