<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Community_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get community by id
     */
    function get_community($id)
    {
        return $this->db->get_where('community',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all community count
     */
    function get_all_community_count()
    {
        $this->db->from('community');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all community
     */
    function get_all_community($params = array())
    {
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('community')->result_array();
    }
        
    /*
     * function to add new community
     */
    function add_community($params)
    {
        $this->db->insert('community',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update community
     */
    function update_community($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('community',$params);
    }
    
    /*
     * function to delete community
     */
    function delete_community($id)
    {
        return $this->db->delete('community',array('id'=>$id));
    }
}
