<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Course_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get course by coursesID
     */
    function get_course($coursesID)
    {
        return $this->db->get_where('courses',array('coursesID'=>$coursesID))->result_array();
    }

    function get_courses($coursesID)
    {
        return $this->db->get_where('courses',array('coursesID'=>$coursesID))->row_array();
    }
    
    /*
     * Get all courses count
     */
    function get_all_courses_count()
    {
        $this->db->from('courses');
        return $this->db->count_all_results();
    }
    

    function get_courses_student($id_student)
    {
        $this->db->select('*');
        $this->db->from('courses');
        $this->db->join('assignedCourses','assignedCourses.courseID=courses.coursesID');
        $this->db->where(['assignedCourses.studentID'=>$id_student]);
        return $this->db->get()->result_array();
    }


    function get_Modules_courses($id_module){
        $this->db->select('*');
        $this->db->from('courses');
        $this->db->join('moduleassign', 'moduleassign.coursesID=courses.coursesID');
        $this->db->where(['moduleassign.moduleID' => $id_module]);
        return $this->db->get()->result_array();
    }

    /*
     *
     * Get all courses
     */
    function get_all_courses($params = array())
    {
        $this->db->order_by('coursesID', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('courses')->result_array();
    }
        

    function get_departement_courses($id){

        $this->db->where(array('courseDepartment'=>$id));
        return $this->db->get('courses')->result_array();
    }
    /*
     * function to add new course
     */
    function add_course($params)
    {
        $this->db->insert('courses',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update course
     */
    function update_course($coursesID,$params)
    {
        $this->db->where('coursesID',$coursesID);
        return $this->db->update('courses',$params);
    }
    
    /*
     * function to delete course
     */
    function delete_course($coursesID)
    {
        return $this->db->delete('courses',array('coursesID'=>$coursesID));
    }

    function get_course_of_departement($id_department){

        $this->db->where('courseDepartment', $id_department);
        return $this->db->get('courses')->result();
    }

    
}
