<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Discussion_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get discussion by discussionID
     */
    function get_discussion($discussionID)
    {
        return $this->db->get_where('discussion',array('discussionID'=>$discussionID))->row_array();
    }
    
    /*
     * Get all discussion count
     */
    function get_all_discussion_count()
    {
        $this->db->from('discussion');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all discussion
     */
    function get_all_discussion($params = array())
    {
        $this->db->order_by('discussionID', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('discussion')->result_array();
    }
        
    /*
     * function to add new discussion
     */
    function add_discussion($params)
    {
        $this->db->insert('discussion',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update discussion
     */
    function update_discussion($discussionID,$params)
    {
        $this->db->where('discussionID',$discussionID);
        return $this->db->update('discussion',$params);
    }
    
    /*
     * function to delete discussion
     */
    function delete_discussion($discussionID)
    {
        return $this->db->delete('discussion',array('discussionID'=>$discussionID));
    }
}
