<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Events_table_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get events_table by id
     */
    function get_events_table($id)
    {
        return $this->db->get_where('events_table',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all events_table count
     */
    function get_all_events_table_count()
    {
        $this->db->from('events_table');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all events_table
     */
    function get_all_events_table($params = array())
    {
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('events_table')->result_array();
    }
        
    /*
     * function to add new events_table
     */
    function add_events_table($params)
    {
        $this->db->insert('events_table',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update events_table
     */
    function update_events_table($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('events_table',$params);
    }
    
    /*
     * function to delete events_table
     */
    function delete_events_table($id)
    {
        return $this->db->delete('events_table',array('id'=>$id));
    }
}
