<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Examfeedback_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get examfeedback by id
     */
    function get_examfeedback($id)
    {
        return $this->db->get_where('examfeedback',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all examfeedback
     */
    function get_all_examfeedback()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('examfeedback')->result_array();
    }
        
    /*
     * function to add new examfeedback
     */
    function add_examfeedback($params)
    {
        $this->db->insert('examfeedback',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update examfeedback
     */
    function update_examfeedback($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('examfeedback',$params);
    }
    
    /*
     * function to delete examfeedback
     */
    function delete_examfeedback($id)
    {
        return $this->db->delete('examfeedback',array('id'=>$id));
    }
}
