<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Exam_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get exam by id
     */
    function get_exam($id)
    {
        return $this->db->get_where('exam',array('id'=>$id))->result_array();
    }
    function get_exams($id)
    {
        return $this->db->get_where('exam',array('id'=>$id))->row_array();
    }

    function get_all_examen_of_module($id_module){

        return $this->db->get_where('exam',array('moduleID'=>$id_module))->result_array();

    }

    
    function get_Exam_of_user($id_module)
    {
        $this->db->select();
        $this->db->from('exam');
        $this->db->join('modules','modules.moduleID=exam.moduleID');
        $this->db->join('courses','courses.coursesID=modules.moduleCourseID');
        $this->db->where(['exam.moduleID'=>$id_module]);
        return $this->db->get()->result_array();
    }

    
    /*
     * Get all exam count
     */
    function get_all_exam_count()
    {
        $this->db->from('exam');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all exam
     */
    function get_all_exam($params = array())
    {
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('exam')->result_array();
    }
        
    /*
     * function to add new exam
     */
    function add_exam($params)
    {
        $this->db->insert('exam',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update exam
     */
    function update_exam($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('exam',$params);
    }
    
    /*
     * function to delete exam
     */
    function delete_exam($id)
    {
        return $this->db->delete('exam',array('id'=>$id));
    }
}
