<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Examanswer_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get examanswer by answerID
     */
    function get_examanswer($answerID)
    {
        return $this->db->get_where('examanswer',array('answerID'=>$answerID))->row_array();
    }
    
    /*
     * Get all examanswer count
     */
    function get_all_examanswer_count()
    {
        $this->db->from('examanswer');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all examanswer
     */
    function get_all_examanswer($params = array())
    {
        $this->db->order_by('answerID', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('examanswer')->result_array();
    }
        
    /*
     * function to add new examanswer
     */
    function add_examanswer($params)
    {
        $this->db->insert('examanswer',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update examanswer
     */
    function update_examanswer($answerID,$params)
    {
        $this->db->where('answerID',$answerID);
        return $this->db->update('examanswer',$params);
    }
    
    /*
     * function to delete examanswer
     */
    function delete_examanswer($answerID)
    {
        return $this->db->delete('examanswer',array('answerID'=>$answerID));
    }
}
