<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Extralesson_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get extralesson by lessonID
     */
    function get_extralesson($lessonID)
    {
        return $this->db->get_where('extralessons',array('lessonID'=>$lessonID))->row_array();
    }
        
    /*
     * Get all extralessons
     */
    function get_all_extralessons()
    {
        $this->db->order_by('lessonID', 'desc');
        return $this->db->get('extralessons')->result_array();
    }
        
    /*
     * function to add new extralesson
     */
    function add_extralesson($params)
    {
        $this->db->insert('extralessons',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update extralesson
     */
    function update_extralesson($lessonID,$params)
    {
        $this->db->where('lessonID',$lessonID);
        return $this->db->update('extralessons',$params);
    }
    
    /*
     * function to delete extralesson
     */
    function delete_extralesson($lessonID)
    {
        return $this->db->delete('extralessons',array('lessonID'=>$lessonID));
    }
}
