<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Feedback_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get feedback by id
     */
    function get_feedback($id)
    {
        return $this->db->get_where('feedback',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all feedback
     */
    function get_all_feedback()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('feedback')->result_array();
    }
        
    /*
     * function to add new feedback
     */
    function add_feedback($params)
    {
        $this->db->insert('feedback',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update feedback
     */
    function update_feedback($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('feedback',$params);
    }
    
    /*
     * function to delete feedback
     */
    function delete_feedback($id)
    {
        return $this->db->delete('feedback',array('id'=>$id));
    }
}
