<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Groupdiscus_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get groupdiscus by id
     */
    function get_groupdiscus($id)
    {
        return $this->db->get_where('groupdiscuss',array('id'=>$id))->row_array();
    }

    /*
     * Get groupdiscus by topic
     */
    function get_groupdiscus_by_topic($topic)
    {
        $this->db->order_by('id','asc');
        return $this->db->get_where('groupdiscuss',array('topicID'=>$topic))->result_array();
    }
        
    /*
     * Get all groupdiscuss
     */
    function get_all_groupdiscuss()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('groupdiscuss')->result_array();
    }
        
    /*
     * function to add new groupdiscus
     */
    function add_groupdiscus($params)
    {
        $this->db->insert('groupdiscuss',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update groupdiscus
     */
    function update_groupdiscus($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('groupdiscuss',$params);
    }
    
    /*
     * function to delete groupdiscus
     */
    function delete_groupdiscus($id)
    {
        return $this->db->delete('groupdiscuss',array('id'=>$id));
    }
}
