<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Learning_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get learning by learningID
     */
    function get_learning($learningID)
    {
        return $this->db->get_where('learning',array('learningID'=>$learningID))->row_array();
    }

    function get_learning_module($id_module){

        return $this->db->get_where('learning',array('moduleID'=>$id_module))->result_array();
    }
        
    /*
     * Get all learning
     */
    function get_all_learning()
    {
        $this->db->order_by('learningID', 'desc');
        return $this->db->get('learning')->result_array();
    }
        
    /*
     * function to add new learning
     */
    function add_learning($params)
    {
        $this->db->insert('learning',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update learning
     */
    function update_learning($learningID,$params)
    {
        $this->db->where('learningID',$learningID);
        return $this->db->update('learning',$params);
    }
    
    /*
     * function to delete learning
     */
    function delete_learning($learningID)
    {
        return $this->db->delete('learning',array('learningID'=>$learningID));
    }
}
