<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Lecturerroom_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get lecturerroom by ID
     */
    function get_lecturerroom($ID)
    {
        return $this->db->get_where('lecturerroom',array('ID'=>$ID))->row_array();
    }
        
    /*
     * Get all lecturerroom
     */
    function get_all_lecturerroom()
    {
        $this->db->order_by('ID', 'desc');
        return $this->db->get('lecturerroom')->result_array();
    }
        
    /*
     * function to add new lecturerroom
     */
    function add_lecturerroom($params)
    {
        $this->db->insert('lecturerroom',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update lecturerroom
     */
    function update_lecturerroom($ID,$params)
    {
        $this->db->where('ID',$ID);
        return $this->db->update('lecturerroom',$params);
    }
    
    /*
     * function to delete lecturerroom
     */
    function delete_lecturerroom($ID)
    {
        return $this->db->delete('lecturerroom',array('ID'=>$ID));
    }
}
