<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Lectureassign_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get lectureassign by AssigneeID
     */
    function get_lectureassign($AssigneeID)
    {
        return $this->db->get_where('lectureassigns',array('AssigneeID'=>$AssigneeID))->row_array();
    }
        
    /*
     * Get all lectureassigns
     */
    function get_all_lectureassigns()
    {
        $this->db->order_by('AssigneeID', 'desc');
        return $this->db->get('lectureassigns')->result_array();
    }
        
    /*
     * function to add new lectureassign
     */
    function add_lectureassign($params)
    {
        $this->db->insert('lectureassigns',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update lectureassign
     */
    function update_lectureassign($AssigneeID,$params)
    {
        $this->db->where('AssigneeID',$AssigneeID);
        return $this->db->update('lectureassigns',$params);
    }
    
    /*
     * function to delete lectureassign
     */
    function delete_lectureassign($AssigneeID)
    {
        return $this->db->delete('lectureassigns',array('AssigneeID'=>$AssigneeID));
    }
}
