<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Lessontopic_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get lessontopic by topicID
     */
    function get_lessontopic($topicID)
    {
        return $this->db->get_where('lessontopic',array('topicID'=>$topicID))->row_array();
    }
    
    /*
     * Get all lessontopic count
     */
    function get_all_lessontopic_count()
    {
        $this->db->from('lessontopic');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all lessontopic
     */
    function get_all_lessontopic($params = array())
    {
        $this->db->order_by('topicID', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('lessontopic')->result_array();
    }
        
    /*
     * function to add new lessontopic
     */
    function add_lessontopic($params)
    {
        $this->db->insert('lessontopic',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update lessontopic
     */
    function update_lessontopic($topicID,$params)
    {
        $this->db->where('topicID',$topicID);
        return $this->db->update('lessontopic',$params);
    }
    
    /*
     * function to delete lessontopic
     */
    function delete_lessontopic($topicID)
    {
        return $this->db->delete('lessontopic',array('topicID'=>$topicID));
    }
}
