<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Management_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get management by managementID
     */
    function get_management($managementID)
    {
        return $this->db->get_where('management',array('managementID'=>$managementID))->row_array();
    }
    
    /*
     * Get all management count
     */
    function get_all_management_count()
    {
        $this->db->from('management');
        return $this->db->count_all_results();
    }

    function auth_management($email,$password) {
		
		$this->db->where(['managementEmail'=>$email,'managementPassword'=>$password]);
		return $this->db->get('management')->result();
	}
        
    /*
     * Get all management
     */
    function get_all_management($params = array())
    {
        $this->db->order_by('managementID', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('management')->result_array();
    }
        
    /*
     * function to add new management
     */
    function add_management($params)
    {
        $this->db->insert('management',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update management
     */
    function update_management($managementID,$params)
    {
        $this->db->where('managementID',$managementID);
        return $this->db->update('management',$params);
    }
    
    /*
     * function to delete management
     */
    function delete_management($managementID)
    {
        return $this->db->delete('management',array('managementID'=>$managementID));
    }
}
