<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Modulematerial_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get modulematerial by moduleID
     */
    function get_modulematerial($moduleID)
    {
        return $this->db->get_where('modulematerial',array('moduleID'=>$moduleID))->row_array();
    }
        
    /*
     * Get all modulematerial
     */
    function get_all_modulematerial()
    {
        $this->db->order_by('moduleID', 'desc');
        return $this->db->get('modulematerial')->result_array();
    }
        
    /*
     * function to add new modulematerial
     */
    function add_modulematerial($params)
    {
        $this->db->insert('modulematerial',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update modulematerial
     */
    function update_modulematerial($moduleID,$params)
    {
        $this->db->where('moduleID',$moduleID);
        return $this->db->update('modulematerial',$params);
    }
    
    /*
     * function to delete modulematerial
     */
    function delete_modulematerial($moduleID)
    {
        return $this->db->delete('modulematerial',array('moduleID'=>$moduleID));
    }
}
