<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Module_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }


    function get_all_module_course($id){

        return $this->db->get_where('modules',array('moduleCourseID'=>$id))->result_array();
    }

    function get_module_course($id_course){

        $this->db->select();
        $this->db->from('modules');
        $this->db->join('courses','courses.coursesID = modules.moduleCourseID');
        $this->db->where(['courses.coursesID'=>$id_course]);

        return $this->db->get()->result_array();
    }
    
    /*
     * Get module by id
     */
    function get_module($id)
    {
        return $this->db->get_where('modules',array('moduleID'=>$id))->row_array();
    }
    function get_module_name($id_module){
        
        return $this->db->get_where('modules',array('moduleID'=>$id_module))->result_array();
    }
    /*
     * Get all modules count
     */
    function get_all_modules_count()
    {
        $this->db->from('modules');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all modules
     */
    function get_all_modules($params = array())
    {
        $this->db->order_by('moduleID', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('modules')->result_array();
    }
        
    /*
     * function to add new module
     */
    function add_module($params)
    {
        $this->db->insert('modules',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update module
     */
    function update_module($id,$params)
    {
        $this->db->where('moduleID',$id);
        return $this->db->update('modules',$params);
    }
    
    /*
     * function to delete module
     */
    function delete_module($id)
    {
        return $this->db->delete('modules',array('moduleID'=>$id));
    }

}
