<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Moduleassign_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get moduleassign by id
     */
    function get_moduleassign($id)
    {
        return $this->db->get_where('moduleassign',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all moduleassign
     */
    function get_all_moduleassign()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('moduleassign')->result_array();
    }
        
    /*
     * function to add new moduleassign
     */
    function add_moduleassign($params)
    {
        $this->db->insert('moduleassign',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update moduleassign
     */
    function update_moduleassign($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('moduleassign',$params);
    }
    
    /*
     * function to delete moduleassign
     */
    function delete_moduleassign($id)
    {
        return $this->db->delete('moduleassign',array('id'=>$id));
    }
}
