<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Parentinfo_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get parentinfo by parentID
     */
    function get_parentinfo($parentID)
    {
        return $this->db->get_where('parentinfo',array('parentID'=>$parentID))->row_array();
    }
        
    /*
     * Get all parentinfo
     */
    function get_all_parentinfo()
    {
        $this->db->order_by('parentID', 'desc');
        return $this->db->get('parentinfo')->result_array();
    }
        
    /*
     * function to add new parentinfo
     */
    function add_parentinfo($params)
    {
        $this->db->insert('parentinfo',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update parentinfo
     */
    function update_parentinfo($parentID,$params)
    {
        $this->db->where('parentID',$parentID);
        return $this->db->update('parentinfo',$params);
    }
    
    /*
     * function to delete parentinfo
     */
    function delete_parentinfo($parentID)
    {
        return $this->db->delete('parentinfo',array('parentID'=>$parentID));
    }
}
