<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Reply_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get reply by id
     */
    function get_reply($id)
    {
        return $this->db->get_where('reply',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all reply
     */
    function get_all_reply()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('reply')->result_array();
    }
        
    /*
     * function to add new reply
     */
    function add_reply($params)
    {
        $this->db->insert('reply',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update reply
     */
    function update_reply($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('reply',$params);
    }
    
    /*
     * function to delete reply
     */
    function delete_reply($id)
    {
        return $this->db->delete('reply',array('id'=>$id));
    }
}
