<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Stafffunction_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get stafffunction by id
     */
    function get_stafffunction($id)
    {
        return $this->db->get_where('stafffunction',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all stafffunction
     */
    function get_all_stafffunction()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('stafffunction')->result_array();
    }
        
    /*
     * function to add new stafffunction
     */
    function add_stafffunction($params)
    {
        $this->db->insert('stafffunction',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update stafffunction
     */
    function update_stafffunction($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('stafffunction',$params);
    }
    
    /*
     * function to delete stafffunction
     */
    function delete_stafffunction($id)
    {
        return $this->db->delete('stafffunction',array('id'=>$id));
    }
}
