<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Teacherfile_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get teacherfile by fileID
     */
    function get_teacherfile($fileID)
    {
        return $this->db->get_where('teacherfiles',array('fileID'=>$fileID))->row_array();
    }
        
    /*
     * Get all teacherfiles
     */
    function get_all_teacherfiles()
    {
        $this->db->order_by('fileID', 'desc');
        return $this->db->get('teacherfiles')->result_array();
    }
        
    /*
     * function to add new teacherfile
     */
    function add_teacherfile($params)
    {
        $this->db->insert('teacherfiles',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update teacherfile
     */
    function update_teacherfile($fileID,$params)
    {
        $this->db->where('fileID',$fileID);
        return $this->db->update('teacherfiles',$params);
    }
    
    /*
     * function to delete teacherfile
     */
    function delete_teacherfile($fileID)
    {
        return $this->db->delete('teacherfiles',array('fileID'=>$fileID));
    }
}
