<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Timetable_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get timetable by id
     */
    function get_timetable($id)
    {
        return $this->db->get_where('timetable',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all timetable
     */
    function get_all_timetable()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('timetable')->result_array();
    }
        
    /*
     * function to add new timetable
     */
    function add_timetable($params)
    {
        $this->db->insert('timetable',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update timetable
     */
    function update_timetable($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('timetable',$params);
    }
    
    /*
     * function to delete timetable
     */
    function delete_timetable($id)
    {
        return $this->db->delete('timetable',array('id'=>$id));
    }
}
