<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Topic_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get topic by id
     */
    function get_topic($id)
    {
        return $this->db->get_where('topics',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all topics
     */
    function get_all_topics()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('topics')->result_array();
    }

    /*
     * Get all topics by module
     */
    function get_all_topics_by_module($moduleID)
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get_where('topics',array('moduleID'=>$moduleID))->result_array();
    }
        
    /*
     * function to add new topic
     */
    function add_topic($params)
    {
        $this->db->insert('topics',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update topic
     */
    function update_topic($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('topics',$params);
    }
    
    /*
     * function to delete topic
     */
    function delete_topic($id)
    {
        return $this->db->delete('topics',array('id'=>$id));
    }
}
